### ISSUE TITLE
Unhandled TaskScheduler exception

### ISSUE THREAD

**Issue by Edward-Bakker** [DurtyFree/durty-cloth-tool#106]
I get an error when I try to open project files V3 when upgrading it to V4. This is on the newest version `2.5.0.3`

```
Unhandled TaskScheduler.UnobservedTaskException exception, A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1'))) in DurtyClothTool.App v2.5.0.3

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')))
 ---> System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1')) (Value cannot be null. (Parameter 'path1'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.a7qtCegedV()
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass23_0.maJDCcR7cG()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
 ---> (Inner Exception #1) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #2) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #3) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #4) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #5) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #6) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #7) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #8) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #9) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #10) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #11) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #12) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at vKBIJa4gcl5ic8aWQU7c.VZJ4wEIDYHT(String , String , vKBIJa4gcl5ic8aWQU7c )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.PedAppearanceItemBase.Df7bHSKAWH0sqrhetDig(Object )
   at DurtyClothTool.App.Models.PedAppearanceItemBase.GetMainFilePath(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.PedAppearanceItemBase.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at DurtyClothTool.App.Models.Cloth.ClothData.UpdateFileContentChecksum(ProjectSettings projectSettings)
   at pGq2QXtkVEmIfP4ZMDS.fJYlyvtu0ptYcwphH74.<>c__DisplayClass24_0.Vh7DDLIirY(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

   --- End of inner exception stack trace ---
```

**Comment by Edward-Bakker** [comment]
fixed in newest version `2.5.0.4`
