### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\Britt\OneDrive\Desktop\SLRP Clothing\SLRPTATS2.0.1\tattoos\.tempwork\Alien hand?.dds'

### ISSUE THREAD

**Issue by ItsHazelsaurus2** [DurtyFree/durty-cloth-tool#135]
I have the following error:
```
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\Britt\OneDrive\Desktop\SLRP Clothing\SLRPTATS2.0.1\tattoos\.tempwork\Alien hand?.dds'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at V3C2wWImDugrQfF8y9ZR.lEoIn5rAbL6(String , Byte[] , V3C2wWImDugrQfF8y9ZR )
   at FmlmIc2zppAWhOnt3yR.ASIhkQ2q0sMf82xSv1G.sXpnOgK9XY(PedAppearanceItemBase  , String  , String  , Boolean  , YtdFile&  )
   at grJKFL2GnvT1rDI5VwM.okgP8l2daTkPqFFhy3C.fKd2hqoS7G(String  , String  )
   at grJKFL2GnvT1rDI5VwM.okgP8l2daTkPqFFhy3C.rZ0IVlpInMx(String  , String  , String  , String  )
   at OeRQwLO9rZ0fScEynnH.U5BfsfOGiXjfWsyMJeA.iJoOhZKliW(Jd3HLntApaCFk1ouB1a  , String  , String  , String  , String  , ProgressDialog  )
```

App Version: **2.5.1.1**
Items: **69 project items (0C / 69D)**
Project targets: **2**
DLC name: **tattoos**
Collection name: **slrptatts // **
Project path: **C:\Users\Britt\Downloads\DurtyClothTool.App\SLRP Tattoos\clothproject_SLRP**
Output path: **C:\Users\Britt\Downloads\DurtyClothTool.App\SLRP Tattoos**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
Last step data:
```JSON
{
  "UvPos": {
    "X": 0.845,
    "Y": 0.68
  },
  "Scale": {
    "X": 0.05,
    "Y": 0.05
  },
  "Rotation": 0.0,
  "NameHash": "Alien hand?_M",
  "TxdHash": "Alien hand?",
  "TxtHash": "Alien hand?",
  "Zone": 5,
  "Type": 1,
  "UpdateGroup": 90,
  "TattooFacing": 2,
  "TargetGender": 0,
  "DateTimeAdded": "2023-06-10T00:25:33.7334985Z",
  "OriginalFileName": "mp_fm_tat_045",
  "MainPath": "ee337f62-2a0b-4b3b-823f-1d019c64af47.ytd",
  "Name": "Alien hand?_M",
  "Position": 13,
  "FileContentChecksum": "29745a75877d1eaa484dfdbac4725f62"
}
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here]`

**Comment by DurtyFree** [comment]
Interesting error, thanks for reporting! I will take a look at this

**Comment by DurtyFree** [comment]
Fixed next update
