### ISSUE TITLE
Value was either too large or too small for an unsigned byte.

### ISSUE THREAD

**Issue by gypsychicken** [DurtyFree/durty-cloth-tool#143]
I have the following error:
```
System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Convert.ToByte(String value)
   at CodeWalker.GameFiles.XmlMeta.Traverse(XmlNode node, MetaBuilder mb, MetaName type, Boolean isRoot)
   at CodeWalker.GameFiles.XmlMeta.Traverse(XmlNode node, MetaBuilder mb, MetaName type, Boolean isRoot)
   at CodeWalker.GameFiles.XmlMeta.GetMeta(XmlDocument doc)
   at o63soGIEtrtpdOmsuh3r.lEoIn5rAbL6(XmlDocument , o63soGIEtrtpdOmsuh3r )
   at FmlmIc2zppAWhOnt3yR.ASIhkQ2q0sMf82xSv1G.bbunwqlpgU(String  , List`1  )
   at grJKFL2GnvT1rDI5VwM.okgP8l2daTkPqFFhy3C.yMJ2HWLrrP(String  , String  , String  , String  )
   at grJKFL2GnvT1rDI5VwM.okgP8l2daTkPqFFhy3C.rZ0IVlpInMx(String  , String  , String  , String  )
   at OeRQwLO9rZ0fScEynnH.U5BfsfOGiXjfWsyMJeA.iJoOhZKliW(Jd3HLntApaCFk1ouB1a  , String  , String  , String  , String  , ProgressDialog  )
```

App Version: **2.5.1.1**
Items: **1992 project items (1992C / 0D)**
Project targets: **2**
DLC name: **mwrpcivclothing**
Collection name: **mwrpcivclothingfull // **
Project path: **H:\MWRPDev\repos\PD-EUP\Durty Clothing Data\clothproject_mwrpcivclothing**
Output path: **H:\MWRPDev\repos\PD-EUP\Durty Clothing Data**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**

Error dialog: https://i.gyazo.com/56a8e7e342ada97dea039a65cc0cc48e.png

```
Cloth files:

**Comment by gypsychicken** [comment]
JSON file : https://www.dropbox.com/scl/fi/4qar94crtr6v4vrercrea/mwrpcivclothing.durty-cloth.json?rlkey=vl53q01k341hsewu9ezasxq35&dl=0

**Comment by DurtyFree** [comment]
Will look into this, thx for reporting :D

**Comment by DurtyFree** [comment]
Anybody has a project or reproduction steps for me?

**Comment by DurtyFree** [comment]
Can't seem to reproduce it, @gypsychicken can you test it with the most recent version and see if the issue still exists?

**Comment by gypsychicken** [comment]
Apologies. This can be closed. I have not had the issue since.

**Comment by DurtyFree** [comment]
Glad to hear, thanks!
