### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by TheRaginKagen** [DurtyFree/durty-cloth-tool#160]
I have the following error:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\FiveM Server files\EUP add-ons - Copy\EUP-NEW-RENAMED\01-11-2024\Connor addons\[v1.0]TLS_Apple_Watch_S8[SC EXCLUSIVE]\[v1.0]TLS_Apple Watch_S8_Pack [SC EXCLUSIVE]\applewatch\stream\mp_m_freemode_01_p_mp_m_applewatch\mp_m_freemode_01_p_mp_m_applewatch^p_lwrist_000.ydd'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at altClothTool.App.Builders.FivemResourceBuilder.CopyPropModelToResource(ClothData propClothData, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\FivemResourceBuilder.cs:line 31
   at altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:line 87
   at altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:line 28

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Please use latest version.
