### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Draguptank** [DurtyFree/durty-cloth-tool#164]
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at g9l8FpoPFumcOZHCsgp.r5ZcyMolxpj5umIcddH.YGVkqlyC7CRPG4lVq4Th(Object )
   at g9l8FpoPFumcOZHCsgp.r5ZcyMolxpj5umIcddH.wf1hCOIFXT(Object  , KeyboardFocusChangedEventArgs  )
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(Tuple`2 postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.PossiblyDeactivate(IntPtr hwndFocus)
   at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.2.2**
Project targets: **2**
DLC name: **Equinox_Clothing_2**
Collection name: **equinox_clothing_2 // **
Project path: **C:\Users\derwi\Downloads\Equinox Clothing\Unzipped Clothes\Equinox_Clothing_2\clothproject_Equinox_Clothing_2**
Output path: **C:\Users\derwi\Downloads\Equinox Clothing\Unzipped Clothes\Equinox_Clothing_2**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Thank you for reporting, I will look into this :)

**Comment by DurtyFree** [comment]
Fixed next hotfix

**Comment by DurtyFree** [comment]
Fixed in https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.3.0
