### ISSUE TITLE
DDS Invalid slice pitch

### ISSUE THREAD

**Issue by aronne0pefkkcpoekk** [DurtyFree/durty-cloth-tool#165]
I have the following error:
```
System.Exception: Invalid slice pitch.
   at DurtyClothTool.App.Common.DdsUtils.GetDDSFile(Texture  )
   at nNlyRvvRUZU77Hr5dDM.yw4cRlv5Y57JTHHAkyC.sOxAMqyqMMk1mMDsPhgK(Object )
   at nNlyRvvRUZU77Hr5dDM.yw4cRlv5Y57JTHHAkyC.nVOvDFdJKc(String  , TextureDictionary  )
   at nNlyRvvRUZU77Hr5dDM.yw4cRlv5Y57JTHHAkyC.b1Pvcr92rF(String  , String  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.jIccb8nc1e(List`1  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.Execute(Object  )
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **bbPack**
Collection name: ** // **
Project path: **C:\Users\adjev\Desktop\Prosans marque Male\clothproject_BommeClothing**
Output path: **C:\Users\adjev\Desktop\Prosans marque Male**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Hi there, thanks for reporting this issue. Can you pls upload the related YDD/YTD file you are trying to optimize? 

Best Regards

**Comment by DurtyFree** [comment]
Hi @MonteurBomme is it possible to provide the related cloth model file pls?

**Comment by DurtyFree** [comment]
I will close this as unresolved for now, please recreate with more details and reproduction steps in the new v3 update.
