### ISSUE TITLE
An XML comment cannot contain '--', and '-' cannot be the last character. Line 2, position 32.

### ISSUE THREAD

**Issue by GREENDNS** [DurtyFree/durty-cloth-tool#166]
I have the following error:
```
System.Xml.XmlException: An XML comment cannot contain '--', and '-' cannot be the last character. Line 2, position 32.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseCDataOrComment(XmlNodeType type, Int32& outStartPos, Int32& outEndPos)
   at System.Xml.XmlTextReaderImpl.ParseCDataOrComment(XmlNodeType type)
   at System.Xml.XmlTextReaderImpl.ParseComment()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at CodeWalker.GameFiles.RpfManager.GetFileXml(String path)
   at CodeWalker.World.TimecycleMods.Init(GameFileCache gameFileCache, Action`1 updateStatus)
   at CodeWalker.World.Weather.Init(GameFileCache gameFileCache, Action`1 updateStatus, Timecycle timecycle)
   at iDDYYIfHhOWLZ7j9YHhn.XGEf4oUTHpC(Object , GameFileCache , Action`1 , Timecycle , iDDYYIfHhOWLZ7j9YHhn )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.SsvyW6BE2C()
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.o2qyQ89SFy()
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **clothespack48**
Collection name: ** // **
Project path: **D:\DurtyClothTool.App (1)\CLOTHESPACK 08.02.2024\clothproject_clothespack48**
Output path: **D:\DurtyClothTool.App (1)\CLOTHESPACK 08.02.2024**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Hi @GREENDNS, thanks for reporting this issue. Can you pls upload the related YDD/YTD file you are trying to optimize?

Best Regards

**Comment by DurtyFree** [comment]
Fixed next update

**Comment by DurtyFree** [comment]
Fixed in https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.3.0
