### ISSUE TITLE
The syntax of the file, directory or volume name is incorrect. C:\Users\adjev\Desktop\Prosans brand Maleimage\HGCKHJ\marque\Cardo" Modworks.png'

### ISSUE THREAD

**Issue by aronne0pefkkcpoekk** [DurtyFree/durty-cloth-tool#169]
I have the following error:
```
System.IO.IOException: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte. : 'C:\Users\adjev\Desktop\Prosans marque Male\image\HGCKHJ\marque\Cardo" Modworks.png'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Create(String path)
   at SixLabors.ImageSharp.IO.LocalFileSystem.Create(String path)
   at SixLabors.ImageSharp.ImageExtensions.Save(Image source, String path, IImageEncoder encoder)
   at SixLabors.ImageSharp.ImageExtensions.SaveAsPng(Image source, String path, PngEncoder encoder)
   at SixLabors.ImageSharp.ImageExtensions.SaveAsPng(Image source, String path)
   at dwDbKXfWz3xT4NAXpGtV.XGEf4oUTHpC(Image , String , dwDbKXfWz3xT4NAXpGtV )
   at nNlyRvvRUZU77Hr5dDM.yw4cRlv5Y57JTHHAkyC.nVOvDFdJKc(String  , TextureDictionary  )
   at nNlyRvvRUZU77Hr5dDM.yw4cRlv5Y57JTHHAkyC.b1Pvcr92rF(String  , String  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.jIccb8nc1e(List`1  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.Execute(Object  )
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **bbPack**
Collection name: ** // **
Project path: **C:\Users\adjev\Desktop\Prosans marque Male\clothproject_BommeClothing**
Output path: **C:\Users\adjev\Desktop\Prosans marque Male**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed next update

**Comment by DurtyFree** [comment]
Fixed in https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.3.0
