### ISSUE TITLE
Invalid slice pitch.

### ISSUE THREAD

**Issue by aronne0pefkkcpoekk** [DurtyFree/durty-cloth-tool#172]
I have the following error:
```
System.Exception: Invalid slice pitch.
   at DurtyClothTool.App.Common.DdsUtils.GetDDSFile(Texture  )
   at nNlyRvvRUZU77Hr5dDM.yw4cRlv5Y57JTHHAkyC.sOxAMqyqMMk1mMDsPhgK(Object )
   at nNlyRvvRUZU77Hr5dDM.yw4cRlv5Y57JTHHAkyC.nVOvDFdJKc(String  , TextureDictionary  )
   at nNlyRvvRUZU77Hr5dDM.yw4cRlv5Y57JTHHAkyC.b1Pvcr92rF(String  , String  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.jIccb8nc1e(List`1  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.Execute(Object  )
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **bbPack**
Collection name: ** // **
Project path: **C:\Users\adjev\Desktop\Prosans marque Male\clothproject_BommeClothing**
Output path: **C:\Users\adjev\Desktop\Prosans marque Male**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
@MonteurBomme Creating new issues for the same problem will not help, pls see my comment here and answer to it thank you.

https://github.com/DurtyFree/durty-cloth-tool/issues/165
