### ISSUE TITLE
3D model open: Name cannot begin with the '0' character, hexadecimal value 0x30

### ISSUE THREAD

**Issue by BigBadKlaus** [DurtyFree/durty-cloth-tool#183]
![image_2024-02-23_191447723](https://github.com/DurtyFree/durty-cloth-tool/assets/161097639/38eff73e-11a6-4394-b08b-4c9019daaa5e)
```
System.Xml.XmlException: Name cannot begin with the '0' character, hexadecimal value 0x30. Line 449, position 58.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at CodeWalker.GameFiles.RpfManager.GetFileXml(String path)
   at CodeWalker.World.TimecycleMods.Init(GameFileCache gameFileCache, Action`1 updateStatus)
   at CodeWalker.World.Weather.Init(GameFileCache gameFileCache, Action`1 updateStatus, Timecycle timecycle)
   at iDDYYIfHhOWLZ7j9YHhn.XGEf4oUTHpC(Object , GameFileCache , Action`1 , Timecycle , iDDYYIfHhOWLZ7j9YHhn )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.SsvyW6BE2C()
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.o2qyQ89SFy()
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Thread.StartCallback()
```

**Comment by DurtyFree** [comment]
Looks like some weirdly made cloth, will look into it for next hotfix

**Comment by DurtyFree** [comment]
Related to #166, Fixed next update

**Comment by DurtyFree** [comment]
Fixed in https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.3.0
