### ISSUE TITLE
Access to the path 'D:\FiveM things\lastexception.txt' is denied.

### ISSUE THREAD

**Issue by djpelie** [DurtyFree/durty-cloth-tool#203]
I have the following error:
```
System.UnauthorizedAccessException: Access to the path 'D:\FiveM things\lastexception.txt' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at SM4EGCf2S86oVHFXTsZE.XGEf4oUTHpC(String , String , SM4EGCf2S86oVHFXTsZE )
   at g5YZCKyLoRBfWbfeAZr.cva0XDymK79KvLRb2HV.E6ByxaiMVk(Exception  , String  )
   at g5YZCKyLoRBfWbfeAZr.cva0XDymK79KvLRb2HV.HYxy2OcviQ(Object  , DispatcherUnhandledExceptionEventArgs  )
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at tBb27pf4JFHIIstxsxKx.XGEf4oUTHpC(Object , tBb27pf4JFHIIstxsxKx )
   at DurtyClothTool.App.App.Main()
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **mpjanuary2016**
Collection name: ** // **
Project path: **D:\FiveM things\clothing output\clothproject_prmvests**
Output path: **D:\FiveM things\clothing output**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed next update

**Comment by DurtyFree** [comment]
Fixed in https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.3.0
