### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Veenah07Ganesh** [DurtyFree/durty-cloth-tool#206]
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DurtyClothTool.App.Renderer.Renderer.BeginRender(DeviceContext  )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.QchJJKymnMuqfCWTHjhV(Object , Object )
   at bNdlL1yMlxMOaaW7Ncj.adqZ3cyKDxO7briDQqn.RenderScene(DeviceContext  )
   at DurtyClothTool.App.Renderer.DirectX.DXManager.Fh9M8iOlaL()
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

App Version: **2.5.2.2**
Project targets: **0**
DLC name: **hulk**
Collection name: ** // **
Project path: **C:\Users\veena\Documents\DurtyClothTool.App\JoaatOutput\clothproject_hulk**
Output path: **C:\Users\veena\Documents\DurtyClothTool.App\JoaatOutput**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed next update, thank you for reporting

**Comment by DurtyFree** [comment]
Fixed in https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.3.0
