### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by osccoding** [DurtyFree/durty-cloth-tool#209]
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AELwuEV9suArmhdjLB0.w6l0FPV3Xx9CIR5fxqm.MLPqRINXbo(Object  , EventArgs  )
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

App Version: **2.5.3.0**
Project targets: **0**
DLC name: **v**
Collection name: ** // **
Project path: **D:\OSC FICHIERS\elevateRP\resources\[Cores]\elevate_clothes\clothproject_Elevate\clothproject_Elevate**
Output path: **D:\OSC FICHIERS\elevateRP\resources\[Cores]\elevate_clothes\clothproject_Elevate**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
