### ISSUE TITLE
The process cannot access the file 'D:\GTA CLOTHES\Apeys Pack\clothproject_test2\data\c2a914ca-1c67-44ea-9896-a94d7ac2a080.png' because it is being used by another process.

### ISSUE THREAD

**Issue by Aprilbean** [DurtyFree/durty-cloth-tool#210]
I have the following error:
```
System.IO.IOException: The process cannot access the file 'D:\GTA CLOTHES\Apeys Pack\clothproject_test2\data\c2a914ca-1c67-44ea-9896-a94d7ac2a080.png' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at v0bc1xVG4wbsIT7yoWGZ.KM7A8qvxIal(String , v0bc1xVG4wbsIT7yoWGZ )
   at bc4SIF1wQW1m6qTg7vC.C3nAnY1P1Q639f4aPv3.r9p1niiBsU()
   at gmYo3Ttx2H9cAepoDoo.xbt2n1touRZLZrOMwxw.QEgHhtgi6q(Object  , RoutedEventArgs  )
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.3.0**
Project targets: **2**
DLC name: **test**
Collection name: ** // **
Project path: **D:\GTA CLOTHES\Apeys Pack\clothproject_test2**
Output path: **D:\GTA CLOTHES\Apeys Pack**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
