### ISSUE TITLE
Invalid slice pitch.

### ISSUE THREAD

**Issue by Kanepkii** [DurtyFree/durty-cloth-tool#211]
I have the following error:
```
System.Exception: Invalid slice pitch.
   at DurtyClothTool.App.Common.DdsUtils.GetDDSFile(Texture  )
   at o1PDcNagGCoOc14BDQu.tBQBJ5apeimyPfD4A8M.hu6PFyVc5lw8HemoD1cE(Object )
   at o1PDcNagGCoOc14BDQu.tBQBJ5apeimyPfD4A8M.CGbal4pOjU(String  , TextureDictionary  )
   at o1PDcNagGCoOc14BDQu.tBQBJ5apeimyPfD4A8M.FlnaS7RIIU(String  , String  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.xHdJH2Vcg9cw7cnAi7vV(Object , Object , Object )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.VNflQXsvnu()
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.Execute(Object  )
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.3.0**
Project targets: **2**
DLC name: **k_frakcje**
Collection name: **k_frakcje // **
Project path: **F:\eup\nowy state\release\state_frakcje\clothproject_k_frakcje**
Output path: **F:\eup\nowy state\release\state_frakcje**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Hi @Kanepkii can you pls attach some clothing (YDD/YTD) files to reproduce this? Thank you!

**Comment by DurtyFree** [comment]
I will close this as unresolved for now, please recreate with more details and reproduction steps in the new v3 update.
