### ISSUE TITLE
Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by devpanda0** [DurtyFree/durty-cloth-tool#218]
I have the following error:
```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at CodeWalker.GameFiles.ResourceBuilder.Build(ResourceFileBase fileBase, Int32 version, Boolean compress)
   at CodeWalker.GameFiles.YtdFile.Save()
   at prmevtAEwMjr9V1ByGLD.KM7A8qvxIal(Object , prmevtAEwMjr9V1ByGLD )
   at fvwe2g6d52fEYW4938k.cv8T8h650qQL6ra57gM.KhB6fxhhbZ(String  , String  )
   at fvwe2g6d52fEYW4938k.cv8T8h650qQL6ra57gM.MiEAlhDkkPQ(String  , String  , String  , String  )
   at fssiOZaQ8QoRdpuGJ0S.CSWWwIadUgjyIuFkcFT.sWZEekVyiG4x9H5exxnl(Object , Object , Object , Object , Object )
   at fssiOZaQ8QoRdpuGJ0S.CSWWwIadUgjyIuFkcFT.FF2afRM8OR(iPQHpsNWc5uo2llQa5F  , String  , String  , String  , String  , ProgressDialog  )
```

App Version: **2.5.3.0**
Items: **17 project items (0C / 17D)**
Project targets: **2**
DLC name: **Tattoos**
Collection name: **tattoos // **
Project path: **C:\Users\chatty\Desktop\dirtyclothtool\Tattoos\clothproject_Tattoos**
Output path: **C:\Users\chatty\Desktop\dirtyclothtool\Tattoos**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
Last step data:
```JSON
{
  "UvPos": {
    "X": 0.233,
    "Y": 0.6
  },
  "Scale": {
    "X": 0.22,
    "Y": 0.21
  },
  "Rotation": 0.0,
  "NameHash": "mp_customtattoo_101",
  "TxdHash": "mp_customtattoo_101",
  "TxtHash": "mp_customtattoo_101",
  "Zone": 5,
  "Type": 1,
  "UpdateGroup": 90,
  "TattooFacing": 2,
  "TargetGender": null,
  "DateTimeAdded": "2024-04-17T19:01:22.2661813Z",
  "OriginalFileName": "1496",
  "MainPath": "9e637f9a-6d99-4481-93a7-e5abd31ad11f.png",
  "Name": "mp_customtattoo_101",
  "Position": 16,
  "FileContentChecksum": "18727430d30dc773d433351202a8fefc"
}
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`
can't upload picture because copyright

**Comment by DurtyFree** [comment]
@devpanda0 pls provide a reproduction project, feel free to send it to me via Discord @durtyfree

**Comment by DurtyFree** [comment]
I will close this as unresolved for now, please recreate with more details and reproduction steps in the new v3 update.
