### ISSUE TITLE
There is not enough space on the disk. : 'C:\Users\User\Desktop\clothproject_astralorgs\data\210b3350-9cf9-43c2-aa55-ac413a77e730.ytd'

### ISSUE THREAD

**Issue by NotLivx** [DurtyFree/durty-cloth-tool#219]
I have the following error:
```
System.IO.IOException: There is not enough space on the disk. : 'C:\Users\User\Desktop\clothproject_astralorgs\data\210b3350-9cf9-43c2-aa55-ac413a77e730.ytd'
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at XR1KplVGr1wJWZbALwud.KM7A8qvxIal(String , String , XR1KplVGr1wJWZbALwud )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.s4hedsvSl0(String  , Byte[]  , String  , Boolean  , Func`2  )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.eMeeUGRaEy(ClothData  , Boolean  , String  , Byte[]  )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.zgPeKZRQGw(List`1  )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.SrGecsGMyn(List`1  )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.VbAebaJHpZ()
   at gmYo3Ttx2H9cAepoDoo.xbt2n1touRZLZrOMwxw.kg7tSY4Rnc(Object  , RoutedEventArgs  )
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.3.0**
Project targets: **0**
DLC name: **astralorgs**
Collection name: ** // **
Project path: **C:\Users\User\Desktop\clothproject_astralorgs**
Output path: **C:\Users\User\Desktop**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Not really a bug, you need more space on your disk.
