### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by dmalhotra2211** [DurtyFree/durty-cloth-tool#221]
I have the following error:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dmalh\Downloads\Whole set\helmet + mask + extra\Male\Helmet Setups\Setup 5 [With Cover]\with Flashlight\p_head_002.ydd'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at altClothTool.App.Builders.FivemResourceBuilder.CopyPropModelToResource(ClothData propClothData, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\FivemResourceBuilder.cs:line 31
   at altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:line 87
   at altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:line 28

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Please use latest version
