### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by ben35329** [DurtyFree/durty-cloth-tool#225]
I have the following error:
System.UnauthorizedAccessException: Access to the path 'C:\dlc.rpf' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at RageLib.GTA5.ArchiveWrappers.RageArchiveWrapper7.Create(String fileName)
   at altClothTool.App.Builders.SingleplayerResourceBuilder.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\SingleplayerResourceBuilder.cs:line 163
   at altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:line 23

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Please use latest version
