### ISSUE TITLE
Invalid slice pitch.

### ISSUE THREAD

**Issue by RustyNeedles81** [DurtyFree/durty-cloth-tool#227]
I have the following error:
```
System.Exception: Invalid slice pitch.
   at DurtyClothTool.App.Common.DdsUtils.GetDDSFile(Texture  )
   at o1PDcNagGCoOc14BDQu.tBQBJ5apeimyPfD4A8M.hu6PFyVc5lw8HemoD1cE(Object )
   at o1PDcNagGCoOc14BDQu.tBQBJ5apeimyPfD4A8M.M00aZPFYPr(String  , TextureDictionary  )
   at o1PDcNagGCoOc14BDQu.tBQBJ5apeimyPfD4A8M.r1Paacvljk(String  , String  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsDdsCommand.saA8amVb5PD4u6nc2GDQ(Object , Object , Object )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsDdsCommand.d0GlFZq4fn()
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsDdsCommand.Execute(Object  )
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.3.0**
Project targets: **0**
DLC name: **dystopia_merge**
Collection name: ** // **
Project path: **C:\EUP\clothproject_dystopia_merge**
Output path: **C:\EUP**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Hi @RustyNeedles81 can you pls provide the related YDD and YTD files?
