### ISSUE TITLE
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Espaço insuficiente no disco. : 'C:\Users\Tiago\Desktop\ROUPAS_AVALON\clothproject_teste\statuslog.txt')

### ISSUE THREAD

**Issue by Tiagomurgia** [DurtyFree/durty-cloth-tool#230]
I have the following error:
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Espaço insuficiente no disco. : 'C:\Users\Tiago\Desktop\ROUPAS_AVALON\clothproject_teste\statuslog.txt')
 ---> System.IO.IOException: Espaço insuficiente no disco. : 'C:\Users\Tiago\Desktop\ROUPAS_AVALON\clothproject_teste\statuslog.txt'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.BufferedFileStreamStrategy.Flush(Boolean flushToDisk)
   at System.IO.Strategies.BufferedFileStreamStrategy.Dispose(Boolean disposing)
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at System.IO.File.InternalWriteAllLines(TextWriter writer, IEnumerable`1 contents)
   at System.IO.File.WriteAllLines(String path, IEnumerable`1 contents)
   at KkrH9xVGCKpWAFLT2nM4.KM7A8qvxIal(String , IEnumerable`1 , KkrH9xVGCKpWAFLT2nM4 )
   at bc4SIF1wQW1m6qTg7vC.C3nAnY1P1Q639f4aPv3.BwK1aX7Z5x(String  )
   at bc4SIF1wQW1m6qTg7vC.C3nAnY1P1Q639f4aPv3.A7I126rc1i()
   at bc4SIF1wQW1m6qTg7vC.C3nAnY1P1Q639f4aPv3.Ntr1bsqSR1()
   at bc4SIF1wQW1m6qTg7vC.C3nAnY1P1Q639f4aPv3.<>c__DisplayClass23_0.xrCM3A4qrj()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

App Version: **2.5.3.0**
Project targets: **0**
DLC name: **teste**
Collection name: ** // **
Project path: **C:\Users\Tiago\Desktop\ROUPAS_AVALON\clothproject_teste**
Output path: **C:\Users\Tiago\Desktop\ROUPAS_AVALON**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Not really a bug, you need more disk space.
