### ISSUE TITLE
Invalid slice pitch.

### ISSUE THREAD

**Issue by VerserVarlin** [DurtyFree/durty-cloth-tool#240]
I have the following error:
```
System.Exception: Invalid slice pitch.
   at DurtyClothTool.App.Common.DdsUtils.GetDDSFile(Texture  )
   at o1PDcNagGCoOc14BDQu.tBQBJ5apeimyPfD4A8M.hu6PFyVc5lw8HemoD1cE(Object )
   at o1PDcNagGCoOc14BDQu.tBQBJ5apeimyPfD4A8M.CGbal4pOjU(String  , TextureDictionary  )
   at o1PDcNagGCoOc14BDQu.tBQBJ5apeimyPfD4A8M.FlnaS7RIIU(String  , String  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.NOMldQdRw3(List`1  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.Execute(Object  )
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.3.0**
Project targets: **2**
DLC name: **julygee_lspd_eup**
Collection name: **julygee_lspd_eup // **
Project path: **C:\Users\name\Desktop\DurtyClothTool.App\output\clothproject_julygee_lspd_eup\clothproject_julygee_lspd_eup**
Output path: **C:\Users\name\Desktop\DurtyClothTool.App\output\clothproject_julygee_lspd_eup**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Hi @VerserVarlin pls attach related YDD and YTD files that give this error, thank you!

**Comment by VerserVarlin** [comment]
it turns out that i have to optimize the file before I extract its texture
