### ISSUE TITLE
The system cannot find the path specified. (0x80070003)

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [DurtyFree/durty-cloth-tool#242]
I have the following error:
```
System.IO.DirectoryNotFoundException: The system cannot find the path specified. (0x80070003)
   at DurtyClothTool.App.Controls.KnownFolders.QTYERayQ7r(Guid  , UInt32  , IntPtr hToken)
   at DurtyClothTool.App.Controls.KnownFolders.GetPath(KnownFolder  )
   at GQvdhkE7A43J3cCl2a5.hGFO0bEA8CgRJVNCMV2.t0XEetZ72V()
   at zdFvh0j8naMVdyOQWLE.YsT4ZLj7mSBhq9sHx48.zZLa0xWPbM(Object  , RadRoutedEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.3.0**
Project targets: **RageMp**
DLC name: **tayspridemerch**
Collection name: **tayspridemerch // **
Project path: **G:\Tays Pride Merch\OUTPUT\clothproject_tayspridemerch**
Output path: **G:\Tays Pride Merch\OUTPUT**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed
