### ISSUE TITLE
Failed to serialize DurtyClothTool.App.Models.ProjectSettings value.

### ISSUE THREAD

**Issue by einsmoka** [DurtyFree/durty-cloth-tool#244]
I have the following error:
```
MessagePack.MessagePackSerializationException: Failed to serialize DurtyClothTool.App.Models.ProjectSettings value.
 ---> System.TypeInitializationException: The type initializer for 'FormatterCache`1' threw an exception.
 ---> MessagePack.Internal.MessagePackDynamicObjectResolverException: can't find matched constructor. type:DurtyClothTool.App.Models.Vector2
   at MessagePack.Internal.ObjectSerializationInfo.CreateOrNull(Type type, Boolean forceStringKey, Boolean contractless, Boolean allowPrivate, Boolean dynamicMethod)
   at MessagePack.Internal.DynamicObjectTypeBuilder.BuildType(DynamicAssembly assembly, Type type, Boolean forceStringKey, Boolean contractless)
   at MessagePack.Resolvers.DynamicObjectResolver.FormatterCache`1..cctor()
   --- End of inner exception stack trace ---
   at MessagePack.Resolvers.DynamicObjectResolver.GetFormatter[T]()
   at MessagePack.Resolvers.StandardResolver.FormatterCache`1..cctor()
--- End of stack trace from previous location ---
   at MessagePack.FormatterResolverExtensions.Throw(TypeInitializationException ex)
   at MessagePack.Formatters.DurtyClothTool_App_Models_Decoration_DecorationDataFormatter3.Serialize(MessagePackWriter& writer, DecorationData value, MessagePackSerializerOptions options)
   at MessagePack.Formatters.ListFormatter`1.Serialize(MessagePackWriter& writer, List`1 value, MessagePackSerializerOptions options)
   at MessagePack.Formatters.DurtyClothTool_App_Models_ProjectSettingsFormatter1.Serialize(MessagePackWriter& writer, ProjectSettings value, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T value, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T value, MessagePackSerializerOptions options)
   at cW5TS423H4QMlQxfq3w.aalSPD2JWA7haXxk2je.p2RYgeYEhN(Object  , Object  )
   at cW5TS423H4QMlQxfq3w.aalSPD2JWA7haXxk2je.ToXVKD0bts65bF8IHtVE(Object , Object )
   at cW5TS423H4QMlQxfq3w.aalSPD2JWA7haXxk2je.q8UYy1ZD8e(String  , Boolean  , Boolean  )
   at cW5TS423H4QMlQxfq3w.aalSPD2JWA7haXxk2je.xVL2sKXn9T()
   at cW5TS423H4QMlQxfq3w.aalSPD2JWA7haXxk2je.ReYYbGiByX(Object sender, ElapsedEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

App Version: **2.5.3.0**
Project targets: **AltV**
DLC name: **clo**
Collection name: **clo // clo**
Project path: **Z:\gta\modding\clo\clothproject_clo**
Output path: **Z:\gta\modding\clo**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed
