### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Kc2693** [DurtyFree/durty-cloth-tool#245]
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Telerik.Windows.Controls.FileDialogs.FileBrowserGridView.Timer_Tick(Object sender, EventArgs e)
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.3.0**
Project targets: **AltV**
DLC name: **ye**
Collection name: ** // **
Project path: **C:\Users\aes12g\Desktop\newtest\clothproject_yep**
Output path: **C:\Users\aes12g\Desktop\newtest**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed
