### ISSUE TITLE
Value cannot be null. (Parameter 'collection')

### ISSUE THREAD

**Issue by MrRenvaldix** [DurtyFree/durty-cloth-tool#246]
I have the following error:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'collection')
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.T1feBxAlph(PedGender  , String[]  )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.UUreuvg9xQ(PedGender  )
   at gmYo3Ttx2H9cAepoDoo.xbt2n1touRZLZrOMwxw.GdPt2saOt0(Object  , RoutedEventArgs  )
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.3.0**
Project targets: **0**
DLC name: **hatorp**
Collection name: **hatorp // **
Project path: **U:\Work_project\Clothes\Alt_v\clothproject_hator**
Output path: **U:\Work_project\Clothes\Alt_v**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed next update

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
