### ISSUE TITLE
Could not find a part of the path 'C:\Users\keira\Desktop\hairs testing\Hair pack final\hairpackfinal.durty-cloth.json'.

### ISSUE THREAD

**Issue by keiraskyler** [DurtyFree/durty-cloth-tool#247]
I have the following error:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\keira\Desktop\hairs testing\Hair pack final\hairpackfinal.durty-cloth.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at OTcxFfAuuIRJst9qtcP7.KM7A8qvxIal(String , String , OTcxFfAuuIRJst9qtcP7 )
   at bc4SIF1wQW1m6qTg7vC.C3nAnY1P1Q639f4aPv3.BwK1aX7Z5x(String  )
   at bc4SIF1wQW1m6qTg7vC.C3nAnY1P1Q639f4aPv3.A7I126rc1i()
   at gmYo3Ttx2H9cAepoDoo.xbt2n1touRZLZrOMwxw.mR6W8pVSwRvsUOZH0IjK(Object )
   at gmYo3Ttx2H9cAepoDoo.xbt2n1touRZLZrOMwxw.aTkt4DIf7r(Object  , RoutedEventArgs  )
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.3.0**
Project targets: **2**
DLC name: **test**
Collection name: **hairpackfinal // **
Project path: **C:\Users\keira\Desktop\DurtyClothTool.App\clothproject_test**
Output path: **C:\Users\keira\Desktop\DurtyClothTool.App**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Should be fixed next update
