### ISSUE TITLE
Failed to serialize DurtyClothTool.App.Models.ProjectCache value.

### ISSUE THREAD

**Issue by sbdonslaught** [DurtyFree/durty-cloth-tool#249]
I have the following error:
```
MessagePack.MessagePackSerializationException: Failed to serialize DurtyClothTool.App.Models.ProjectCache value.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at MessagePack.Formatters.CollectionFormatterBase`4.Serialize(MessagePackWriter& writer, TCollection value, MessagePackSerializerOptions options)
   at MessagePack.Formatters.DurtyClothTool_App_Models_ProjectCacheFormatter12.Serialize(MessagePackWriter& writer, ProjectCache value, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T value, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T value, MessagePackSerializerOptions options)
   at xWJDBW5i8ZZZjvwNSNs.DYYP2i5BwMov6TUL4Vo.udL5HS1JQe()
   at mIc0hw2f7x5bG44ZBwP.xgswe729L6qmUW8XI81.F28ePBUvpnCZNb6Xwrfe(Object )
   at mIc0hw2f7x5bG44ZBwP.xgswe729L6qmUW8XI81.hVI2uLYjUq(String  , Boolean  , Boolean  )
   at mIc0hw2f7x5bG44ZBwP.xgswe729L6qmUW8XI81.qdf2DfQ09i()
   at mIc0hw2f7x5bG44ZBwP.xgswe729L6qmUW8XI81.gA22SKlAHf(Object sender, ElapsedEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

App Version: **2.5.3.0**
Project targets: **FiveM**
DLC name: **highlife_clothing_01**
Collection name: **highlife_clothing_01 // **
Project path: **C:\clothing_source\projects\clothproject_highlife_clothing_01**
Output path: **C:\clothing_source\projects**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed
