### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SoGiovaah** [DurtyFree/durty-cloth-tool#250]
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AELwuEV9suArmhdjLB0.w6l0FPV3Xx9CIR5fxqm.Ax9qb5UOlA(Object  , EventArgs  )
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

App Version: **2.5.3.0**
Project targets: **0**
DLC name: **italianliferoleplay**
Collection name: ** // **
Project path: **F:\[fivem_dev]\[ILRPP]\[Output]\clothproject_ItalianLifeRolePlay**
Output path: **F:\[fivem_dev]\[ILRPP]\[Output]**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Should be fixed next update
