### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by luvmad** [DurtyFree/durty-cloth-tool#251]
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AELwuEV9suArmhdjLB0.w6l0FPV3Xx9CIR5fxqm.RTmqcOW2AY(Object  , EventArgs  )
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

App Version: **2.5.3.0**
Project targets: **0**
DLC name: **MadisonV1**
Collection name: ** // **
Project path: **E:\MadisonV1\clothproject_MadisonV1**
Output path: **E:\MadisonV1**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Should be fixed next update
