### ISSUE TITLE
Access to the path 'C:\Users\morbi\OneDrive\Desktop\savages\clothproject_savages\data' is denied.

### ISSUE THREAD

**Issue by YourMaker757** [DurtyFree/durty-cloth-tool#259]
I have the following error:
```
System.UnauthorizedAccessException: Access to the path 'C:\Users\morbi\OneDrive\Desktop\savages\clothproject_savages\data' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at I1GEsRAUvdspGNs9JlN9.KM7A8qvxIal(String , I1GEsRAUvdspGNs9JlN9 )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.s4hedsvSl0(String  , Byte[]  , String  , Boolean  , Func`2  )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.zgPeKZRQGw(List`1  )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.T1feBxAlph(PedGender  , String[]  )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.UUreuvg9xQ(PedGender  )
   at gmYo3Ttx2H9cAepoDoo.xbt2n1touRZLZrOMwxw.GdPt2saOt0(Object  , RoutedEventArgs  )
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.3.0**
Project targets: **0**
DLC name: **savages**
Collection name: ** // **
Project path: **C:\Users\morbi\OneDrive\Desktop\savages\clothproject_savages**
Output path: **C:\Users\morbi\OneDrive\Desktop\savages**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Choose another location
