### ISSUE TITLE
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (Collection was modified; enumeration operation may not execute.) (Collection was modified; enumeration operation may not execute.))

### ISSUE THREAD

**Issue by sbdonslaught** [DurtyFree/durty-cloth-tool#265]
I have the following error:
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (Collection was modified; enumeration operation may not execute.) (Collection was modified; enumeration operation may not execute.))
 ---> System.AggregateException: One or more errors occurred. (Collection was modified; enumeration operation may not execute.) (Collection was modified; enumeration operation may not execute.)
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at xWJDBW5i8ZZZjvwNSNs.DYYP2i5BwMov6TUL4Vo.nJ15kQI432(PedAppearanceItemBase  )
   at xWJDBW5i8ZZZjvwNSNs.DYYP2i5BwMov6TUL4Vo.JCs5FGISBn(PedAppearanceItemBase  )
   at mIc0hw2f7x5bG44ZBwP.xgswe729L6qmUW8XI81.<>c__DisplayClass38_0.xMOhaZUV6UBIyhvlOocV(Object , Object )
   at mIc0hw2f7x5bG44ZBwP.xgswe729L6qmUW8XI81.<>c__DisplayClass38_0.MqS4olbG1ob(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at mIc0hw2f7x5bG44ZBwP.xgswe729L6qmUW8XI81.WGT2yE4meR()
   at mIc0hw2f7x5bG44ZBwP.xgswe729L6qmUW8XI81.<>c__DisplayClass32_0.TN444CYkQCx()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
 ---> (Inner Exception #1) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at xWJDBW5i8ZZZjvwNSNs.DYYP2i5BwMov6TUL4Vo.nJ15kQI432(PedAppearanceItemBase  )
   at xWJDBW5i8ZZZjvwNSNs.DYYP2i5BwMov6TUL4Vo.JCs5FGISBn(PedAppearanceItemBase  )
   at mIc0hw2f7x5bG44ZBwP.xgswe729L6qmUW8XI81.<>c__DisplayClass38_0.xMOhaZUV6UBIyhvlOocV(Object , Object )
   at mIc0hw2f7x5bG44ZBwP.xgswe729L6qmUW8XI81.<>c__DisplayClass38_0.MqS4olbG1ob(PedAppearanceItemBase pedAppearanceItemBase)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

   --- End of inner exception stack trace ---
```

App Version: **2.5.3.0**
Project targets: **FiveM**
DLC name: **highlife_clothing_01**
Collection name: **highlife_clothing_01 // **
Project path: **C:\clothing_source\projects\clothproject_highlife_clothing_01**
Output path: **C:\clothing_source\projects**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed next update
