### ISSUE TITLE
Invalid slice pitch.

### ISSUE THREAD

**Issue by cageFX** [DurtyFree/durty-cloth-tool#271]
I have the following error:
```
System.Exception: Invalid slice pitch.
   at DurtyClothTool.App.Common.DdsUtils.GetDDSFile(Texture  )
   at o1PDcNagGCoOc14BDQu.tBQBJ5apeimyPfD4A8M.hu6PFyVc5lw8HemoD1cE(Object )
   at o1PDcNagGCoOc14BDQu.tBQBJ5apeimyPfD4A8M.CGbal4pOjU(String  , TextureDictionary  )
   at o1PDcNagGCoOc14BDQu.tBQBJ5apeimyPfD4A8M.FlnaS7RIIU(String  , String  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.xHdJH2Vcg9cw7cnAi7vV(Object , Object , Object )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.VNflQXsvnu()
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsPngCommand.Execute(Object  )
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **2.5.3.0**
Project targets: **0**
DLC name: **roots_test**
Collection name: ** // **
Project path: **C:\Users\KayCh\Desktop\DurtyClothTool.App\clothproject_roots_test**
Output path: **C:\Users\KayCh\Desktop\DurtyClothTool.App**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **4**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
#211 Duplicate
