### ISSUE TITLE
Drag and Dropping a new file crashes/ importing from folder crashes.

### ISSUE THREAD

**Issue by PoppiDemon** [DurtyFree/durty-cloth-tool#272]
https://github.com/user-attachments/assets/6a6667ad-6702-4628-9c9d-8ce3b4fe3a24

I have the following error:
```
System.InvalidOperationException: The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
   at System.Windows.FrameworkElement.EnsureFrameworkServices()
   at System.Windows.FrameworkElement..ctor()
   at System.Windows.Controls.Control..ctor()
   at System.Windows.Controls.HeaderedContentControl..ctor()
   at Telerik.Windows.Controls.WindowBase..ctor()
   at Telerik.Windows.Controls.RadWindow..ctor()
   at DurtyClothTool.App.Views.ConfirmationDialogWindow..ctor(String  , String  , String  , String  , String  , PackIconFontAwesomeKind  )
   at yXwxZK5dVY38GJmAFqH.XetIN45lItS8qERcxif.P1w5SpRcWv(Object  , Object  , String  , String  , String  , PackIconFontAwesomeKind  )
   at cCSXhJSC1xSb5mKrB0j.aJ72WuSqclbySWheSuW.okR9f4k5oG(String  , Byte[]  , String  , Boolean  , Func`2  )
   at cCSXhJSC1xSb5mKrB0j.aJ72WuSqclbySWheSuW.AVe9KScnTX(ClothData  , Boolean  , String  , Byte[]  , Boolean  )
   at cCSXhJSC1xSb5mKrB0j.aJ72WuSqclbySWheSuW.JaI9yPZelx(List`1  , Boolean  )
   at cCSXhJSC1xSb5mKrB0j.aJ72WuSqclbySWheSuW.<>c__DisplayClass41_0.pQwERxmhOIQ()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at cCSXhJSC1xSb5mKrB0j.aJ72WuSqclbySWheSuW.N5T9coABTy(Nullable`1  , String[]  )
   at hO5wuXBIhlsYd7vvbDE.KruLmDB11prT9Jt44XP.RAjJjdigSq(Object  , DragEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.0**
Project targets: **FiveM**
DLC name: **poppinerpemsleo**
Collection name: **poppiemsleo // **
Project path: **D:\3D Models\GTA\PoppiPack\poppiemsleonerp\clothproject_poppinerpemsleo**
Output path: **D:\3D Models\GTA\PoppiPack\poppiemsleonerp**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed in new minor update, thanks for reporting!
