### ISSUE TITLE
The calling thread must be STA, because many UI components require this.

### ISSUE THREAD

**Issue by Sammehbrah** [DurtyFree/durty-cloth-tool#273]
I have the following error:
```
System.InvalidOperationException: The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
   at System.Windows.FrameworkElement.EnsureFrameworkServices()
   at System.Windows.FrameworkElement..ctor()
   at System.Windows.Controls.Control..ctor()
   at Telerik.Windows.Controls.WindowBase..ctor()
   at Telerik.Windows.Controls.RadWindow..ctor()
   at DurtyClothTool.App.Views.ConfirmationDialogWindow..ctor(String  , String  , String  , String  , String  , PackIconFontAwesomeKind  )
   at yXwxZK5dVY38GJmAFqH.XetIN45lItS8qERcxif.P1w5SpRcWv(Object  , Object  , String  , String  , String  , PackIconFontAwesomeKind  )
   at cCSXhJSC1xSb5mKrB0j.aJ72WuSqclbySWheSuW.okR9f4k5oG(String  , Byte[]  , String  , Boolean  , Func`2  )
   at cCSXhJSC1xSb5mKrB0j.aJ72WuSqclbySWheSuW.JaI9yPZelx(List`1  , Boolean  )
   at cCSXhJSC1xSb5mKrB0j.aJ72WuSqclbySWheSuW.<>c__DisplayClass37_0.r41EEW3xv6e()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at cCSXhJSC1xSb5mKrB0j.aJ72WuSqclbySWheSuW.OU29vbLhU8(PedGender  )
   at hO5wuXBIhlsYd7vvbDE.KruLmDB11prT9Jt44XP.sGRBXK8MxQ(Object  , RoutedEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.0**
Project targets: **AltV**
DLC name: **hiveeupplus_v3**
Collection name: ** // **
Project path: **E:\FiveM-GTA stuff\HIVERP\Hive Clothes\2Rebuilding\HiveEUPplus_v3\1.Durty Project Files\clothproject_hiveeupplus_v3**
Output path: **E:\FiveM-GTA stuff\HIVERP\Hive Clothes\2Rebuilding\HiveEUPplus_v3\1.Durty Project Files**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Hi there please restart your app / redownload DCT. This should be fixed with update 3.0.0.1
