### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Sammehbrah** [DurtyFree/durty-cloth-tool#274]
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.RenameSelectedClothTextureCommand.kQfHe7AfyIFDWVys28KD(Object )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.RenameSelectedClothTextureCommand.CanExecute(Object  )
   at Telerik.Windows.Controls.RadMenuItem.CanExecuteApply()
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Windows.Input.CommandManager.RaiseRequerySuggested(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.1**
Project targets: **AltV**
DLC name: **hiveeupplus_v3**
Collection name: ** // **
Project path: **E:\FiveM-GTA stuff\HIVERP\Hive Clothes\2Rebuilding\HiveEUPplus_v3\1.Durty Project Files\clothproject_hiveeupplus_v3**
Output path: **E:\FiveM-GTA stuff\HIVERP\Hive Clothes\2Rebuilding\HiveEUPplus_v3\1.Durty Project Files**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed with new hotfix v3.0.0.2, auto updater should prompt for it, alternatively you can grab it from the releases.
