### ISSUE TITLE
Could not find a part of the path 'C:\Users\Lauren\Desktop\Clothing Packs\Project Nova\Clothing Pack\clothproject_projectnovard\lastautobackup.dctproj'.

### ISSUE THREAD

**Issue by Meelicks** [DurtyFree/durty-cloth-tool#275]
I have the following error:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Lauren\Desktop\Clothing Packs\Project Nova\Clothing Pack\clothproject_projectnovard\lastautobackup.dctproj'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at VuGexAUX7aEtWrHIDa8n.c56U6d66HZs(String , Byte[] , VuGexAUX7aEtWrHIDa8n )
   at OnBQd4GF5jCHbt0P3PE.hRrRI5GXPsR5VSsBsxL.Iy1VucxNRE(Object  , Object  )
   at OnBQd4GF5jCHbt0P3PE.hRrRI5GXPsR5VSsBsxL.TNYVQAv8an(String  , Boolean  , Boolean  )
   at OnBQd4GF5jCHbt0P3PE.hRrRI5GXPsR5VSsBsxL.s3sV84jf5g()
   at OnBQd4GF5jCHbt0P3PE.hRrRI5GXPsR5VSsBsxL.JJhVM9NZxX(Object sender, ElapsedEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

App Version: **3.0.0.1**
Project targets: **FiveM**
DLC name: **projectnovard**
Collection name: **recklessdesigns // **
Project path: **C:\Users\Lauren\Desktop\Clothing Packs\Project Nova\Clothing Pack\clothproject_projectnovard**
Output path: **C:\Users\Lauren\Desktop\Clothing Packs\Project Nova\Clothing Pack**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed with new hotfix v3.0.0.2, auto updater should prompt for it, alternatively you can grab it from the releases.
