### ISSUE TITLE
Could not find a part of the path 'D:\Admiration FiveM\bb Pack Bomme Full\Projets\test\clothproject_test\data'.

### ISSUE THREAD

**Issue by aronne0pefkkcpoekk** [DurtyFree/durty-cloth-tool#278]
I have the following error:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Admiration FiveM\bb Pack Bomme Full\Projets\test\clothproject_test\data'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at zD3Zj7UZsLxvdtX1kRIR.c56U6d66HZs(String , zD3Zj7UZsLxvdtX1kRIR )
   at HcCWG7kjmBtJuEBU7iP.LjKhF6kcfC2vTGC9otg.N9CPXSCYyg(String  , Byte[]  , String  , Boolean  , Func`2  )
   at HcCWG7kjmBtJuEBU7iP.LjKhF6kcfC2vTGC9otg.pLwPmSl4hG(List`1  , Boolean  )
   at HcCWG7kjmBtJuEBU7iP.LjKhF6kcfC2vTGC9otg.<>c__DisplayClass36_0.rGgUUdWCBkF()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at HcCWG7kjmBtJuEBU7iP.LjKhF6kcfC2vTGC9otg.APAPn2TMMb(List`1  )
   at HcCWG7kjmBtJuEBU7iP.LjKhF6kcfC2vTGC9otg.wATPbnU8A9()
   at yB6ANrQnuTZLrsN3Ai1.wmctpaQbEaR6hM7wa8n.CMGQq1OWcv(Object  , RoutedEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.1**
Project targets: **AltV**
DLC name: **bb**
Collection name: ** // **
Project path: **D:\Admiration FiveM\bb Pack Bomme Full\Projets\test\clothproject_test**
Output path: **D:\Admiration FiveM\bb Pack Bomme Full\Projets\test**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed with new hotfix v3.0.0.2, auto updater should prompt for it, alternatively you can grab it from the releases.
