### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by keiraskyler** [DurtyFree/durty-cloth-tool#289]
I have the following error:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at uVHg75RqqqY24XrdaEQ4.SO1RSccveye(Object , Formatting , uVHg75RqqqY24XrdaEQ4 )
   at SGwSpSx0BNVapLXRE4s.CcfiVsxVIGgGTtSSufZ.iJ6xGbQ2eE()
   at SGwSpSx0BNVapLXRE4s.CcfiVsxVIGgGTtSSufZ.CIkxnwBk8m()
   at jPQlHyVKwGgMT2R05AC.JWGNI4VjUbPci1EpiAB.eu4CS4FSneUfj1OHl5RO(Object )
   at jPQlHyVKwGgMT2R05AC.JWGNI4VjUbPci1EpiAB.QmwVYrcPyZ(Object  , EventArgs  )
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.2**
Project targets: **AltV**
DLC name: **shoesoundtest**
Collection name: ** // **
Project path: **D:\Novalyfe\shoesoundtest\clothproject_shoesoundtest**
Output path: **D:\Novalyfe\shoesoundtest**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed in patch .5, either update thru the auto updater or grab the latest release from: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
