### ISSUE TITLE
The process cannot access the file 'E:\VPRP\DurtyClothTool.App\vprp_civil_homme\clothproject_vprp_civil_homme\lastautobackup.dctproj' because it is being used by another process.

### ISSUE THREAD

**Issue by julie-desvaux** [DurtyFree/durty-cloth-tool#293]
I have the following error:
```
System.IO.IOException: The process cannot access the file 'E:\VPRP\DurtyClothTool.App\vprp_civil_homme\clothproject_vprp_civil_homme\lastautobackup.dctproj' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at ho5F2UrU8nKxsGN9UW3X.z0BrS27C0Li(String , Byte[] , ho5F2UrU8nKxsGN9UW3X )
   at Cg6QdoMLJe0U8amoZnZ.zTS5b1MAEFcE5tdgtFG.pRFMGmqmHv(Object  , Object  )
   at Cg6QdoMLJe0U8amoZnZ.zTS5b1MAEFcE5tdgtFG.HUdMPt5ewE(String  , Boolean  , Boolean  )
   at Cg6QdoMLJe0U8amoZnZ.zTS5b1MAEFcE5tdgtFG.zaRMFEMKnw()
   at Cg6QdoMLJe0U8amoZnZ.zTS5b1MAEFcE5tdgtFG.RPqMeOSU11(Object sender, ElapsedEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

App Version: **3.0.0.4**
Project targets: **FiveM**
DLC name: **vprp_civil_homme**
Collection name: **vprp_civil_homme // **
Project path: **E:\VPRP\DurtyClothTool.App\vprp_civil_homme\clothproject_vprp_civil_homme**
Output path: **E:\VPRP\DurtyClothTool.App\vprp_civil_homme**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed in patch .5, either update thru the auto updater or grab the latest release from: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
