### ISSUE TITLE
The added or subtracted value results in an un-representable DateTime. (Parameter 'value')

### ISSUE THREAD

**Issue by Eclipsin** [DurtyFree/durty-cloth-tool#297]
I have the following error:
```
System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime. (Parameter 'value')
   at System.DateTime.ThrowDateArithmetic(Int32 param)
   at System.DateTime.AddTicks(Int64 value)
   at qiTBZTp9MVmNKfPwL585.FQ05PhUNO2r(DateTime& , Int64 , qiTBZTp9MVmNKfPwL585 )
   at rrxiI7dKSRWACqiCLkb.mVIBVtdDW1Owjg6je9k.nqblhk5c3Cc7fAPctQVb..ctor(BinaryReader  )
   at rrxiI7dKSRWACqiCLkb.mVIBVtdDW1Owjg6je9k.DY1dIG8MF7(Object  )+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at eIE9rkcU6KDDrIRACXr.eo7BsncxtVX489u8Hra.zmKFkPa1nD(Object  , DragEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.5**
Project targets: **FiveM**
DLC name: **whereuat**
Collection name: ** // **
Project path: **E:\Backups 4-08-24\### A SEQUEL\Klær\Whereuat\clothproject_whereuat**
Output path: **E:\Backups 4-08-24\### A SEQUEL\Klær\Whereuat**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed in patch .6, either update thru the auto updater or grab the latest release from: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
