### ISSUE TITLE
Could not find a part of the path 'H:\SCRP Clothing\clothproject_cgscrp5'.

### ISSUE THREAD

**Issue by zacharytbaldino** [DurtyFree/durty-cloth-tool#308]
I have the following error:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'H:\SCRP Clothing\clothproject_cgscrp5'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at cZcWTiUyb6ElGDJlD2Aw.lXQU3rgV66n(String , cZcWTiUyb6ElGDJlD2Aw )
   at mTH7bRauTT9us2EmQ3U.i60ZyQapHH0e6OoyylT.t0iabcDiAl(String  )
   at mTH7bRauTT9us2EmQ3U.i60ZyQapHH0e6OoyylT.ESJa35Emig()
   at WLkf2WShNkbIoq87FSp.flybkqSlvU3NWfblxmB.ttAYDrB3mHNTO28aKgRe(Object )
   at WLkf2WShNkbIoq87FSp.flybkqSlvU3NWfblxmB.PRJSDWIpG4(Object  , RoutedEventArgs  )
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at Telerik.Windows.Controls.RadButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.6**
Project targets: **FiveM**
DLC name: **cgscrp5**
Collection name: **nzscrpp5 // **
Project path: **H:\SCRP Clothing\clothproject_cgscrp5**
Output path: **H:\SCRP Clothing**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by zacharytbaldino** [comment]
This happened when running the build project to my external hard disk. May have been a windows issue but reported just in case

**Comment by DurtyFree** [comment]
Fixed in patch .7, either update thru the auto updater or grab the latest release from: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
