### ISSUE TITLE
Value cannot be null. (Parameter 'path1')

### ISSUE THREAD

**Issue by Eclipsin** [DurtyFree/durty-cloth-tool#311]
I have the following error:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at CExAYFUNHvjlHKiyDXRk.lXQU3rgV66n(String , String , CExAYFUNHvjlHKiyDXRk )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.Cloth.ClothTextureData.hZ0W2l8ixbWE8ffWZDKR(Object )
   at DurtyClothTool.App.Models.Cloth.ClothTextureData.GetFilePath(ProjectSettings projectSettings)
   at uZKuHqtoRPnbAQXnNdp.Pmw1JPtCPYVc9wyoyq1.<>c__DisplayClass38_0.csaKilU4ca7XTPTHTroi.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

App Version: **3.0.0.6**
Project targets: **FiveM**
DLC name: **sequel**
Collection name: **seqmaincloth // **
Project path: **F:\### SEQUEL KLÆR\KLESPAKKE\clothproject_sequel**
Output path: **F:\### SEQUEL KLÆR\KLESPAKKE**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed in patch .7, either update thru the auto updater or grab the latest release from: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
