### ISSUE TITLE
Access to the path 'C:\Users\minde\Desktop\Klamotten\durty\clothproject_addon2' is denied.

### ISSUE THREAD

**Issue by GhostikGER** [DurtyFree/durty-cloth-tool#314]
I have the following error:
```
System.UnauthorizedAccessException: Access to the path 'C:\Users\minde\Desktop\Klamotten\durty\clothproject_addon2' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at K4yngH4pDPkW5TMKP4xk.Yl04VCQ1NH6(String , K4yngH4pDPkW5TMKP4xk )
   at L7R5sMLESO5Y0RIenXo.YKaeW8LDWNYLt15Nyfe.gZKLzhLkfS()
   at L7R5sMLESO5Y0RIenXo.YKaeW8LDWNYLt15Nyfe.h2JLWrVljP(String  )
   at L7R5sMLESO5Y0RIenXo.YKaeW8LDWNYLt15Nyfe.QIaLvYnRQv(Object  , PropertyChangedEventArgs  )
   at DurtyClothTool.App.Models.PropertyChangedBase.<>c__DisplayClass3_0.Bg4NoXeC4luUjeibI7GN(Object , Object , Object )
   at DurtyClothTool.App.Models.PropertyChangedBase.<>c__DisplayClass3_0.A4Z4XPOZQjj()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.7**
Project targets: **FiveM**
DLC name: **addon**
Collection name: **addon2 // **
Project path: **D:\Resourcen\Klamotten\Klamotten\durty\clothproject_addon2**
Output path: **D:\Resourcen\Klamotten\Klamotten\durty**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed in latest release Hotfix .8, get it from here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
