### ISSUE TITLE
Value cannot be null. (Parameter 'path1')

### ISSUE THREAD

**Issue by MissBlue91** [DurtyFree/durty-cloth-tool#317]
I have the following error:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at af3wRt4uTOlaMBTeUnlV.Yl04VCQ1NH6(String , String , af3wRt4uTOlaMBTeUnlV )
   at DurtyClothTool.App.Models.ProjectSettings.get_ProjectFolderPath()
   at DurtyClothTool.App.Models.ProjectSettings.get_DataFilesFolderPath()
   at DurtyClothTool.App.Models.Cloth.ClothTextureData.WLSZiTexNs9PxTZHj5r7(Object )
   at DurtyClothTool.App.Models.Cloth.ClothTextureData.GetFilePath(ProjectSettings projectSettings)
   at yk3kvyNQQXEcc7qwaSP.YkWXZtN7vBbFBFB7R9N.<>c__DisplayClass38_0.DcmDVr4qVjvDIPcNwnxP.gWQkdmeZxDclVI659qQN(Object , Object )
   at yk3kvyNQQXEcc7qwaSP.YkWXZtN7vBbFBFB7R9N.<>c__DisplayClass38_0.DcmDVr4qVjvDIPcNwnxP.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

App Version: **3.0.0.7**
Project targets: **AltV**
DLC name: ****
Collection name: ** // **
Project path: **D:\DurtyClothTool.App\Output\OldCityClothes2Redo\clothproject_**
Output path: **D:\DurtyClothTool.App\Output\OldCityClothes2Redo**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed in latest release Hotfix .8, get it from here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
