### ISSUE TITLE
The given key 'Hair' was not present in the dictionary.

### ISSUE THREAD

**Issue by drhannibalseca** [DurtyFree/durty-cloth-tool#318]
I have the following error:
```
System.Collections.Generic.KeyNotFoundException: The given key 'Hair' was not present in the dictionary.
   at wlrQg8Kv8DZRYlD0sgG.nJTfPpKVBBvuOsUw6vQ.W82eJWphkL()
   at wlrQg8Kv8DZRYlD0sgG.nJTfPpKVBBvuOsUw6vQ.hq4emTyLe3(Object  , PropertyChangedEventArgs  )
   at DurtyClothTool.App.Models.PropertyChangedBase.<>c__DisplayClass3_0.Bg4NoXeC4luUjeibI7GN(Object , Object , Object )
   at DurtyClothTool.App.Models.PropertyChangedBase.<>c__DisplayClass3_0.A4Z4XPOZQjj()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.7**
Project targets: **FiveM**
DLC name: **lalalandbikerpack**
Collection name: **lalalandbikerpack // **
Project path: **C:\Users\secaf\OneDrive\Desktop\lalalandbikerpack\clothproject_lalalandbikerpack**
Output path: **C:\Users\secaf\OneDrive\Desktop\lalalandbikerpack**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed in latest release Hotfix .8, get it from here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
