### ISSUE TITLE
Multiple files selected - the FileNames property should be used instead.

### ISSUE THREAD

**Issue by alenochkabt** [DurtyFree/durty-cloth-tool#320]
I have the following error:
```
System.InvalidOperationException: Multiple files selected - the FileNames property should be used instead.
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.get_FileName()
   at DI54JxK6GQNTtGbqEudu.Yl04VCQ1NH6(Object , DI54JxK6GQNTtGbqEudu )
   at QbPZrFHZgIa8XfGGOP1.v73iTWHpLmviJqnddIs.sU2HAKi4BI(Object  , Object  , String&  , List`1&  , Boolean  )
   at QbPZrFHZgIa8XfGGOP1.v73iTWHpLmviJqnddIs.ViIHbfTZYC(Object  , Object  , String&  , List`1&  , Boolean  , Boolean  )
   at pnW4EwkwwMNfTsGLuTn.C53tSVkswWwliJ6xK6r.uTOkWN8K8W(Nullable`1  )
   at pnW4EwkwwMNfTsGLuTn.C53tSVkswWwliJ6xK6r.ztIkUofN0s(PedGender  )
   at SgTKk7Ya4qrAHPg7aID.b40uwvYhDckHOoIDiWl.znGY6m6iJh(Object  , RoutedEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.7**
Project targets: **FiveM**
DLC name: **mgclothingfem4**
Collection name: **mgclothingfem3 // **
Project path: **C:\Users\onaes\OneDrive\Рабочий стол\testim na servake azoru\FOR THE SERVER\Final mgclothingfem4\clothproject_mgclothingfem4**
Output path: **C:\Users\onaes\OneDrive\Рабочий стол\testim na servake azoru\FOR THE SERVER\Final mgclothingfem4**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
Any clothing items shoulkd be selected (more than one) and trying to be added

**Comment by DurtyFree** [comment]
Fixed in latest release Hotfix .8, get it from here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
