### ISSUE TITLE
Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by tday130** [DurtyFree/durty-cloth-tool#324]
I have the following error:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: There is not enough space on the disk. : 'C:\Users\nazbo\Downloads\JuiceFireClothingPackV1\JuiceFireClothingPackV1\stream\mp_m_freemode_01_mp_m_juicebigpackv1\humblebeastremastered.dctproj'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at OE3lEs4AKrQxXGSACh24.Yl04VCQ1NH6(String , Byte[] , OE3lEs4AKrQxXGSACh24 )
   at yk3kvyNQQXEcc7qwaSP.YkWXZtN7vBbFBFB7R9N.QpLNjMUuC0(Object  , Object  )
   at yk3kvyNQQXEcc7qwaSP.YkWXZtN7vBbFBFB7R9N.sjVpDeecViSHxSVnZ34e(Object , Object )
   at yk3kvyNQQXEcc7qwaSP.YkWXZtN7vBbFBFB7R9N.xorNIBsXRw(String  , Boolean  , Boolean  )
   at yk3kvyNQQXEcc7qwaSP.YkWXZtN7vBbFBFB7R9N.nZiN5YmxOV()
   at SgTKk7Ya4qrAHPg7aID.b40uwvYhDckHOoIDiWl.P0oCaPKvmZ7enSPlRd3d(Object )
   at SgTKk7Ya4qrAHPg7aID.b40uwvYhDckHOoIDiWl.gOfYn3pURU(Object  , RoutedEventArgs  )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.RoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at Telerik.Windows.Controls.RadMenuItem.OnClickImpl()
   at Telerik.Windows.Controls.RadMenuItem.HandleMouseUp()
   at Telerik.Windows.Controls.RadMenuItem.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.7**
Project targets: **FiveM**
DLC name: **humblebeastofficialclothing**
Collection name: **juiceofficialclothing // **
Project path: **C:\Users\nazbo\Downloads\DurtyClothTool.App (2)\DurtyClothTool.App\clothproject_humblebeastofficialclothing**
Output path: **C:\Users\nazbo\Downloads\DurtyClothTool.App (2)\DurtyClothTool.App**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Hi @tday130 please make sure you have enough space on your disk, the disk the project is being saved too is full.
