### ISSUE TITLE
The given key 'Body' was not present in the dictionary.

### ISSUE THREAD

**Issue by zyrex41222** [DurtyFree/durty-cloth-tool#325]
I have the following error:
```
System.Collections.Generic.KeyNotFoundException: The given key 'Body' was not present in the dictionary.
   at wlrQg8Kv8DZRYlD0sgG.nJTfPpKVBBvuOsUw6vQ.TDxeLZAhEA()
   at wlrQg8Kv8DZRYlD0sgG.nJTfPpKVBBvuOsUw6vQ.fl6eZ7cZ2t(Object  , EventArgs  )
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

App Version: **3.0.0.7**
Project targets: **AltV**
DLC name: **tttete**
Collection name: ** // **
Project path: **C:\Users\zyrex\Desktop\durtycloth\clothproject_tttete**
Output path: **C:\Users\zyrex\Desktop\durtycloth**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed in latest release Hotfix .8, get it from here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
