### ISSUE TITLE
Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.

### ISSUE THREAD

**Issue by Shihiro1** [DurtyFree/durty-cloth-tool#328]
I have the following error:
```
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.IO.MemoryStream..ctor(Byte[] buffer, Int32 index, Int32 count, Boolean writable, Boolean publiclyVisible)
   at System.IO.MemoryStream..ctor(Byte[] buffer, Int32 index, Int32 count)
   at CodeWalker.GameFiles.ResourceDataReader..ctor(RpfResourceFileEntry resentry, Byte[] data, Endianess endianess)
   at CodeWalker.GameFiles.YtdFile.Load(Byte[] data, RpfFileEntry entry)
   at CodeWalker.GameFiles.RpfFile.LoadResourceFile[T](T file, Byte[] data, UInt32 ver)
   at CodeWalker.GameFiles.YtdFile.Load(Byte[] data)
   at Lwy7j74CwmllsNBNSX9u.Yl04VCQ1NH6(Object , Byte[] , Lwy7j74CwmllsNBNSX9u )
   at uxV0vw2uTB5MCqX6QOm.DmDRIL2vFBo7i9HhnZL.QA92yT2N8v(String  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.OptimizeSelectedClothTextureCommand.y64jXbwDEF(DmDRIL2vFBo7i9HhnZL  , ClothTextureData  , GRokgF8CxhFRmjCfELD  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.OptimizeSelectedClothTextureCommand.Execute(Object  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.7**
Project targets: **FiveM**
DLC name: **v2_au_rp_clothing**
Collection name: **aurp_v204 // **
Project path: **E:\Users\Jenny\Pictures\Youtube\GTA RP\Adelaide RP Clothing\clothproject_v2_au_rp_clothing**
Output path: **E:\Users\Jenny\Pictures\Youtube\GTA RP\Adelaide RP Clothing**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Hi there seems like this YTD is corrupted for some case, this will be catched upcoming update

**Comment by DurtyFree** [comment]
Fixed in latest release Hotfix .8, get it from here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
