### ISSUE TITLE
One or more errors occurred. (Could not find a part of the path 'C:\Users\sonny\Desktop\Neu 3\clothproject_westehomeland\data\2df5ac52-3a32-41fb-a611-85c87c4b405d.ydd'.)

### ISSUE THREAD

**Issue by alexweinberg333** [DurtyFree/durty-cloth-tool#331]
I have the following error:
```
System.AggregateException: One or more errors occurred. (Could not find a part of the path 'C:\Users\sonny\Desktop\Neu 3\clothproject_westehomeland\data\2df5ac52-3a32-41fb-a611-85c87c4b405d.ydd'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\sonny\Desktop\Neu 3\clothproject_westehomeland\data\2df5ac52-3a32-41fb-a611-85c87c4b405d.ydd'.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Fl3f2h4M2bne6vxiHxeE.Yl04VCQ1NH6(String , String , Boolean , Fl3f2h4M2bne6vxiHxeE )
   at Xyi41VI49I6VdSvd1Rc.zmTBHDIXMrw6McPqTDE.I9v4UzORfcG(ClothData  , Int32  , String  , String  , String  , String  , String  , Boolean  , String  )
   at wK3e8qcdjm0c3ifLe69.bfBIwxcmYRdjJOl2xvm.<>c__DisplayClass14_0.KHsXrve9wNDDdEOmjIHc(Object , Object , Int32  , Object , Object , Object , Object , Object , Boolean  , Object )
   at wK3e8qcdjm0c3ifLe69.bfBIwxcmYRdjJOl2xvm.<>c__DisplayClass14_0.HpNMoxmrIg()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at mgctxcKXPVRK52Me70LA.Yl04VCQ1NH6(Task[] , mgctxcKXPVRK52Me70LA )
   at wK3e8qcdjm0c3ifLe69.bfBIwxcmYRdjJOl2xvm.srtcaImrOB(String  , String  , String  , List`1  , Int32  )
   at wK3e8qcdjm0c3ifLe69.bfBIwxcmYRdjJOl2xvm.x0Cch6Ou7p(String  , String  , String  , String  )
   at wK3e8qcdjm0c3ifLe69.bfBIwxcmYRdjJOl2xvm.YGC4WPZZ1Ma(String  , String  , String  , String  )
   at YJ9XSiIhq7kJjOEPtIE.BqODX2ILVF0779tApxy.dl0dWNKp3fLssu6hkekO(Object , Object , Object , Object , Object )
   at YJ9XSiIhq7kJjOEPtIE.BqODX2ILVF0779tApxy.EFGIaJxccM(TargetResourceType  , String  , String  , String  , String  , ProgressDialog  )
```

App Version: **3.0.0.7**
Items: **1 project items (1C / 0D)**
Project targets: **FiveM**
DLC name: **westehomeland**
Collection name: **westehomeland // **
Project path: **C:\Users\sonny\Desktop\Neu 3\clothproject_westehomeland**
Output path: **C:\Users\sonny\Desktop\Neu 3**
Disable Extra Ymt Creation: **True**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
Last step data:
```JSON
{
  "Textures": [
    {
      "OriginalFileName": "mp_m_freemode_01_mp_m_january2016^task_diff_001_a_uni",
      "IsDummy": false,
      "FilePath": "fece9fc6-514e-4e26-ae84-130dd1813ced.ytd",
      "Position": 0,
      "Id": "eb68be48-4370-42d0-9899-71460ccf2116",
      "DateTimeAdded": "2024-09-20T22:06:56.2846169Z",
      "DateTimeModified": "2024-09-20T22:06:56.2843352Z",
      "FirstPersonTimeCycleModifier": null,
      "FirstPersonTimeCycleModifierIntensity": 1.0,
      "FileContentChecksum": "52e7094933bc0ba57627fc8b00c2ac87"
    }
  ],
  "PedComponentFlags": {
    "HighHeelHeight": 1.0,
    "Flag5": false
  },
  "PedComponentOptions": {
    "FirstPersonData": {
      "FpsPropModel": null,
      "PutOnTakeOffAnimEnabled": false
    },
    "Flags": 0,
    "CutHairs": false,
    "HideHairs": false,
    "HoodieHars": false
  },
  "PedPropFlags": {},
  "PedPropOptions": {
    "HairCutValue": 0.0,
    "FirstPersonData": {
      "FpsPropModel": null,
      "PutOnTakeOffAnimEnabled": false
    },
    "PropFlags": 0,
    "RemoveHatInVehicle": false,
    "IsMotorcycleHelmet": false,
    "IsBulletproofHelmet": false,
    "IsAirplaneHat": false,
    "CutHairs": false,
    "HideHairs": false,
    "CustomCutHairs": false
  },
  "IsDummy": false,
  "ClothType": 0,
  "DrawableSkinType": 0,
  "FirstPersonModelFilePath": null,
  "AlternationModelFilePathTwo": null,
  "AlternationModelFilePathThree": null,
  "MeshPhysicsFilePath": null,
  "DrawableType": 9,
  "AudioPreset": 0,
  "Id": "d1dea2d0-9126-4a08-b656-29dfba201b27",
  "TargetGender": 0,
  "DateTimeAdded": "2024-09-20T22:06:55.7502798Z",
  "OriginalFileName": "mp_m_freemode_01_mp_m_january2016^task_001_u.ydd",
  "MainPath": "2df5ac52-3a32-41fb-a611-85c87c4b405d.ydd",
  "Name": "Armor",
  "Position": 0,
  "FileContentChecksum": "7259f83014f452b52d57654029fe908f"
}
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Not able to fix this as this is related to some weird project setup, please contact me via DM on discord if you have this issue again.
