### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by the1andonlyCarmine** [DurtyFree/durty-cloth-tool#333]
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at wlrQg8Kv8DZRYlD0sgG.nJTfPpKVBBvuOsUw6vQ.A8XKuaUi1G()
   at wlrQg8Kv8DZRYlD0sgG.nJTfPpKVBBvuOsUw6vQ.lO0eAI5n8r(Object  , EventArgs  )
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

App Version: **3.0.0.7**
Project targets: **FiveM**
DLC name: **mp2024_01**
Collection name: **mp_m_2024_01 // mp_f_2024_01**
Project path: **C:\Users\admin\Desktop\Zombie 2.0\clothproject_cloud9test**
Output path: **C:\Users\admin\Desktop\Zombie 2.0**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: mp2024_01**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Fixed in latest release Hotfix .8, get it from here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
