### ISSUE TITLE
Invalid slice pitch.

### ISSUE THREAD

**Issue by Rossebma** [DurtyFree/durty-cloth-tool#334]
I have the following error:
```
System.Exception: Invalid slice pitch.
   at DurtyClothTool.App.Common.DdsUtils.GetDDSFile(Texture  )
   at GGcObM0mbblFR82rnOw.elDrpT0JuxNUhCmkWJY.qg6pmtKyZ1vCcWW6Ombq(Object )
   at GGcObM0mbblFR82rnOw.elDrpT0JuxNUhCmkWJY.fd10wkWaZG(String  , TextureDictionary  )
   at GGcObM0mbblFR82rnOw.elDrpT0JuxNUhCmkWJY.PY80PZnhbs(String  , String  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsDdsCommand.cxrjDLJjl3(List`1  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.ClothTexture.Export.ExportClothTextureAsDdsCommand.Execute(Object  )
   at Telerik.Windows.Controls.RadMenuItem.ExecuteCommand()
   at Telerik.Windows.Controls.RadMenuItem.OnClickImpl()
   at Telerik.Windows.Controls.RadMenuItem.OnClick()
   at Telerik.Windows.Controls.RadMenuItem.ClickItem()
   at Telerik.Windows.Controls.RadMenuItem.HandleMouseUp()
   at Telerik.Windows.Controls.RadMenuItem.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.7**
Project targets: **FiveM**
DLC name: **blfivepd_leo_v3_0**
Collection name: **blpd_leo_v3_0 // **
Project path: **F:\Design\EUP\BlueLine\Law Enforcement\V3\-- export --\clothproject_blfivepd_leo_v3_0**
Output path: **F:\Design\EUP\BlueLine\Law Enforcement\V3\-- export --**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**

Cloth files:
[a](https://github.com/user-attachments/assets/0eb1e728-b7f8-48de-8cd0-7a66fe2bd2a5)
-> happens when I try to downscale this picture which I imported into DCT as a PNG

**Comment by Rossebma** [comment]
So It seems like I fixed it. 
1. I restarted my PC. 
2. Then I installed the NVIDIA Texture Tools standalone

**Comment by DurtyFree** [comment]
Interesting, happy to hear its fixed now
