### ISSUE TITLE
illegal position!

### ISSUE THREAD

**Issue by kanjutkudaaaaa** [DurtyFree/durty-cloth-tool#338]
I have the following error:
```
System.Exception: illegal position!
   at CodeWalker.GameFiles.ResourceDataReader.ReadFromStream(Int32 count, Boolean ignoreEndianess)
   at CodeWalker.GameFiles.DataReader.ReadString()
   at CodeWalker.GameFiles.ResourceDataReader.ReadStringAt(UInt64 position)
   at CodeWalker.GameFiles.Meta.Read(ResourceDataReader reader, Object[] parameters)
   at CodeWalker.GameFiles.ResourceDataReader.ReadBlock[T](Object[] parameters)
   at CodeWalker.GameFiles.PedFile.Load(Byte[] data, RpfFileEntry entry)
   at CodeWalker.GameFiles.RpfManager.GetFile[T](RpfEntry e)
   at CodeWalker.GameFiles.GameFileCache.<>c__DisplayClass213_0.<InitPeds>b__3(IEnumerable`1 from)
   at CodeWalker.GameFiles.GameFileCache.InitPeds()
   at CodeWalker.GameFiles.GameFileCache.InitDlc()
   at CodeWalker.GameFiles.GameFileCache.Init(Action`1 updateStatus, Action`1 errorLog)
   at nmPpNesQDEpm6PudkL74.c9ysrR0Ya75(Object , Action`1 , Action`1 , nmPpNesQDEpm6PudkL74 )
   at QyidskhrMRmUy7PsINZ.Hs2W6Vh9c4x7l4hVTqn.kgshAKNodA()
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Thread.StartCallback()
```

App Version: **3.0.0.8**
Project targets: **AltV**
DLC name: **mp_fiveproject_pack_one**
Collection name: ** // **
Project path: **D:\mp_fiveproject_one\clothproject_mp_fiveproject_pack_one**
Output path: **D:\mp_fiveproject_one**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
This seems to be related by a modded GTA V installation, we are not supporting this I am sorry.
