### ISSUE TITLE
Access to the path 'C:\WINDOWS\system32\.temp\mp_f_freemode_01_mp_f_^berd_004_u' is denied.

### ISSUE THREAD

**Issue by Scorpion7162** [DurtyFree/durty-cloth-tool#347]
I have the following error:
```
System.UnauthorizedAccessException: Access to the path 'C:\WINDOWS\system32\.temp\mp_f_freemode_01_mp_f_^berd_004_u' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at CtAOc3s2pTEaUanLiFGP.c9ysrR0Ya75(String , CtAOc3s2pTEaUanLiFGP )
   at n0iP71N6GqdDXUVeVhM.hyjW9BN4Q4CgH5dYQZx.q1YNdgIRrh(ProjectContext  , PedAppearanceItemBase  , String  , Byte[]&  , String&  )
   at n0iP71N6GqdDXUVeVhM.hyjW9BN4Q4CgH5dYQZx.GaNND7fQQq(ProjectContext  , ClothData  , String  , Byte[]&  , String&  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.OptimizeAppearanceItemCommand.Execute(Object  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.8**
Project targets: **AltV**
DLC name: **swathats2**
Collection name: ** // **
Project path: **C:\Users\Scorpion\Desktop\clothproject_swathats2**
Output path: **C:\Users\Scorpion\Desktop\**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Please choose another folder or check whether your windows / antivirus settings are blocking access to the given folder.
