### ISSUE TITLE
Access to the path 'D:\New folder\NE DL\DurtyClothTool.App\DurtyClothTool.App\.temp\mp_m_freemode_01_mp_m_^jbib_000_u' is denied.

### ISSUE THREAD

**Issue by einna0606** [DurtyFree/durty-cloth-tool#357]
I have the following error:
```
System.UnauthorizedAccessException: Access to the path 'D:\New folder\NE DL\DurtyClothTool.App\DurtyClothTool.App\.temp\mp_m_freemode_01_mp_m_^jbib_000_u' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at CtAOc3s2pTEaUanLiFGP.c9ysrR0Ya75(String , CtAOc3s2pTEaUanLiFGP )
   at n0iP71N6GqdDXUVeVhM.hyjW9BN4Q4CgH5dYQZx.q1YNdgIRrh(ProjectContext  , PedAppearanceItemBase  , String  , Byte[]&  , String&  )
   at n0iP71N6GqdDXUVeVhM.hyjW9BN4Q4CgH5dYQZx.GaNND7fQQq(ProjectContext  , ClothData  , String  , Byte[]&  , String&  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.OptimizeAppearanceItemCommand.Execute(Object  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.0.0.8**
Project targets: **AltV**
DLC name: **coat**
Collection name: ** // **
Project path: **C:\Users\einna\Downloads\clothproject_alakdan\clothproject_coat**
Output path: **C:\Users\einna\Downloads\clothproject_alakdan**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Handled next update
