### ISSUE TITLE
InvalidArgument=Value of '0' is not valid for 'SelectedIndex'. (Parameter 'value')Actual value was 0.

### ISSUE THREAD

**Issue by Eclipsin** [DurtyFree/durty-cloth-tool#362]
I have the following error:
```
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'SelectedIndex'. (Parameter 'value')
Actual value was 0.
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at VFsFMSiN4glf1MoOKVAc.Jgjia9Kf0Wj(Object , Int32 , VFsFMSiN4glf1MoOKVAc )
   at neqNTfSGl3ps7uPNy7o.dPqZVMS55gExp2RTgoq.tTBr1h1h6A(Object  , EventArgs  )
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.set_Checked(Boolean value)
   at oemd4AidLFKeggNErbnF.Jgjia9Kf0Wj(Object , Boolean , oemd4AidLFKeggNErbnF )
   at neqNTfSGl3ps7uPNy7o.dPqZVMS55gExp2RTgoq.HyxVUMlNXX()
   at neqNTfSGl3ps7uPNy7o.dPqZVMS55gExp2RTgoq.InitScene(Device  )
   at DurtyClothTool.App.Renderer.DirectX.DXManager.Start()
   at DurtyClothTool.App.Renderer.Renderer.Start()
   at neqNTfSGl3ps7uPNy7o.dPqZVMS55gExp2RTgoq.nyFVfVMbZW()
   at neqNTfSGl3ps7uPNy7o.dPqZVMS55gExp2RTgoq.DJqVYCf8CI(Object  , EventArgs  )
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

App Version: **3.1.0.0**
Project targets: **FiveM**
DLC name: **sequel**
Collection name: **seqpakke1 // **
Project path: **F:\### SEQUEL KLÆR\KLESPAKKE\clothproject_sequel**
Output path: **F:\### SEQUEL KLÆR\KLESPAKKE**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Please update to latest Hotfix 1
