### ISSUE TITLE
System.OverflowException: Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by oklizzy** [DurtyFree/durty-cloth-tool#366]
I have the following error:
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Arithmetic operation resulted in an overflow.)
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at CodeWalker.GameFiles.ResourceBuilder.Build(ResourceFileBase fileBase, Int32 version, Boolean compress)
   at CodeWalker.GameFiles.YtdFile.Save()
   at z1tKCgmxyQZGFN2m6OlZ.F0A1TdY1cEI(Object , z1tKCgmxyQZGFN2m6OlZ )
   at el3CORNxi6mECAUFSCl.jxcFcuNK3s3Y7mPYTBY.X9kNiHpuEa(String[]  )
   at el3CORNxi6mECAUFSCl.jxcFcuNK3s3Y7mPYTBY.<>c__DisplayClass15_0.SDRlxf1aQ35YRYSyuF7F.MoveNext()
   --- End of inner exception stack trace ---
```

App Version: **3.1.0.3**
Project targets: **AltV**
DLC name: **roots_tattoo_pack_2**
Collection name: ** // **
Project path: **C:\Users\mandy\Desktop\roots-tattoo-pack-2\clothproject_roots_tattoo_pack_2**
Output path: **C:\Users\mandy\Desktop\roots-tattoo-pack-2**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Should be fixed in latest release v3.2 and later, please test it if possible and let me know when its not fixed :D

Get the latest version here: https://github.com/DurtyFree/durty-cloth-tool/releases
