### ISSUE TITLE
System.IO.IOException: Access to the path is denied.

### ISSUE THREAD

**Issue by 1795214163** [DurtyFree/durty-cloth-tool#368]
I have the following error:
```
System.IO.IOException: Access to the path '\\?\C:\Users\candy\OneDrive\Desktop\Durty Tool\DurtyClothTool.App\.temp\mp_m_freemode_01_mp_m_^feet_004_u\mp_m_freemode_01_mp_m_^feet_004_u' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at aUIbKSmrKViJp1LieV0J.F0A1TdY1cEI(String , Boolean , aUIbKSmrKViJp1LieV0J )
   at Mirx5xOKgm0ekAiTtZb.QPBS0vOFLUYduYE3sNv.uoMOO3dpAd(ProjectContext  , PedAppearanceItemBase  , String  , Byte[]&  , String&  )
   at Mirx5xOKgm0ekAiTtZb.QPBS0vOFLUYduYE3sNv.vsXODKxpvP(ProjectContext  , ClothData  , String  , Byte[]&  , String&  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.OptimizeClothItemCommand.Execute(Object  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.1.0.3**
Project targets: **AltV**
DLC name: **reckless2clothing**
Collection name: ** // **
Project path: **C:\Users\candy\Downloads\FiveM Clothing\Clothing 2.0\Reg Clothing\clothproject_reckless2clothing**
Output path: **C:\Users\candy\Downloads\FiveM Clothing\Clothing 2.0\Reg Clothing**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Should be fixed in latest release v3.2 and later, please test it if possible and let me know when its not fixed :D

Get the latest version here: https://github.com/DurtyFree/durty-cloth-tool/releases
