### ISSUE TITLE
System.IO.IOException: Datafeil (sirkulerende overflødighetskontroll, CRC).

### ISSUE THREAD

**Issue by Eclipsin** [DurtyFree/durty-cloth-tool#369]
I have the following error:
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Datafeil (sirkulerende overflødighetskontroll, CRC). : 'E:\Backups 4-08-24\### A SEQUEL\SeqPakke2\SEQPAKKE2NEW\clothproject_seqpakke2skytmeg\data\94345419-3716-4242-982c-3e9505895260.ytd')
 ---> System.IO.IOException: Datafeil (sirkulerende overflødighetskontroll, CRC). : 'E:\Backups 4-08-24\### A SEQUEL\SeqPakke2\SEQPAKKE2NEW\clothproject_seqpakke2skytmeg\data\94345419-3716-4242-982c-3e9505895260.ytd'
   at System.IO.Strategies.OSFileStreamStrategy.Read(Span`1 buffer)
   at System.IO.Strategies.OSFileStreamStrategy.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(Span`1 destination, ArraySegment`1 arraySegment)
   at System.IO.Strategies.BufferedFileStreamStrategy.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Security.Cryptography.HashAlgorithm.ComputeHash(Stream inputStream)
   at ExCBDkmYTBQPSFiDWS4N.F0A1TdY1cEI(Object , Stream , ExCBDkmYTBQPSFiDWS4N )
   at wmhXRK7ACAV76OaKRfZ.nw1UVv7PJQoAdoG2MGQ.UTS4WwDAVt(String  )
   at wmhXRK7ACAV76OaKRfZ.nw1UVv7PJQoAdoG2MGQ.B784mC9BC7(ClothData  , ClothTextureData  )
   at wmhXRK7ACAV76OaKRfZ.nw1UVv7PJQoAdoG2MGQ.zCh7NNYZMr(PedAppearanceItemBase  , ConcurrentBag`1  )
   at wmhXRK7ACAV76OaKRfZ.nw1UVv7PJQoAdoG2MGQ.GPF7TUSnXH(PedAppearanceItemBase  )
   at XHU06q40rmocTklyoJR.Gm79964wYtdaxTxTX7U.I6G42Sb1h2()
   at XHU06q40rmocTklyoJR.Gm79964wYtdaxTxTX7U.<>c__DisplayClass31_0.gki1x9VhLje()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

App Version: **3.1.0.3**
Project targets: **FiveM**
DLC name: **seqpakke2skytmeg**
Collection name: **seqpakke2new // **
Project path: **E:\Backups 4-08-24\### A SEQUEL\SeqPakke2\SEQPAKKE2NEW\clothproject_seqpakke2skytmeg**
Output path: **E:\Backups 4-08-24\### A SEQUEL\SeqPakke2\SEQPAKKE2NEW**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by Eclipsin** [comment]
Hi! Im really new to github. But is there a fix to this? Im about to loose a lot of work for like the third time if i have to redo this heh.. Also sorry for sending 2, I forgot that i had allready sent one, my memory is a bit bad.. c,:
Thanks for taking your time to look at it and help ^-^

**Comment by DurtyFree** [comment]
Should be fixed in latest release v3.2 and later, please test it if possible and let me know when its not fixed :D

Get the latest version here: https://github.com/DurtyFree/durty-cloth-tool/releases
