### ISSUE TITLE
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by Eclipsin** [DurtyFree/durty-cloth-tool#371]
I have the following error:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at ixgEbs1sDUPZhZjQoJ8d.F0A1TdY1cEI(Object , ixgEbs1sDUPZhZjQoJ8d )
   at foQM16KEUkT9SqMSgSP.Ynd8kQKXg2Xtdr7Hnrx.A51KKSkjUR(Object  , NotifyCollectionChangedEventArgs  )
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.SetItem(Int32 index, T item)
   at fAFtTTf9Ae0SCjnvdMe.zc4cwWfE8egyErUlCIT.OAx70MbgZo()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at fAFtTTf9Ae0SCjnvdMe.zc4cwWfE8egyErUlCIT.aO37rc6P0g()
   at fAFtTTf9Ae0SCjnvdMe.zc4cwWfE8egyErUlCIT.KOGfB7sDNG(ClothData  , Boolean  )
   at fAFtTTf9Ae0SCjnvdMe.zc4cwWfE8egyErUlCIT.Frlf8MXdHv(List`1  , Boolean  )
   at fAFtTTf9Ae0SCjnvdMe.zc4cwWfE8egyErUlCIT.<>c__DisplayClass40_0.mD81rCTHMdY()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at fAFtTTf9Ae0SCjnvdMe.zc4cwWfE8egyErUlCIT.moifqL3lmX(PedGender  )
   at X6YNI7J4l9LbBtgI1qL.SnArITJ7eL2MsK5h8pI.iwCtcdTbX0(Object  , RoutedEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.1.0.3**
Project targets: **AltV**
DLC name: **seqpakke2del5**
Collection name: ** // **
Project path: **E:\Backups 4-08-24\### A SEQUEL\seq2nr5skytmeg\clothproject_seqpakke2del5**
Output path: **E:\Backups 4-08-24\### A SEQUEL\seq2nr5skytmeg**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by DurtyFree** [comment]
Should be fixed in latest release v3.2 and later, please test it if possible and let me know when its not fixed :D

Get the latest version here: https://github.com/DurtyFree/durty-cloth-tool/releases
