### ISSUE TITLE
System.IO.IOException: The file or directory is corrupted and unreadable.

### ISSUE THREAD

**Issue by TayDzn** [DurtyFree/durty-cloth-tool#372]
I have the following error:
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The file or directory is corrupted and unreadable. : 'D:\Users\Owen\Desktop\GTA\Durty Cloth Tool\clothproject_mpfemale\data\f24ac305-0a93-43a1-bdf0-a02c6cfb5905.ytd')
 ---> System.IO.IOException: The file or directory is corrupted and unreadable. : 'D:\Users\Owen\Desktop\GTA\Durty Cloth Tool\clothproject_mpfemale\data\f24ac305-0a93-43a1-bdf0-a02c6cfb5905.ytd'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at fck3shmYAUy7ox7Dk3Kg.F0A1TdY1cEI(String , fck3shmYAUy7ox7Dk3Kg )
   at wmhXRK7ACAV76OaKRfZ.nw1UVv7PJQoAdoG2MGQ.UTS4WwDAVt(String  )
   at wmhXRK7ACAV76OaKRfZ.nw1UVv7PJQoAdoG2MGQ.B784mC9BC7(ClothData  , ClothTextureData  )
   at wmhXRK7ACAV76OaKRfZ.nw1UVv7PJQoAdoG2MGQ.zCh7NNYZMr(PedAppearanceItemBase  , ConcurrentBag`1  )
   at wmhXRK7ACAV76OaKRfZ.nw1UVv7PJQoAdoG2MGQ.GPF7TUSnXH(PedAppearanceItemBase  )
   at XHU06q40rmocTklyoJR.Gm79964wYtdaxTxTX7U.I6G42Sb1h2()
   at XHU06q40rmocTklyoJR.Gm79964wYtdaxTxTX7U.<>c__DisplayClass31_0.gki1x9VhLje()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

App Version: **3.1.0.3**
Project targets: **FiveM**
DLC name: **mpfemale**
Collection name: **mpfemale // **
Project path: **D:\Users\Owen\Desktop\GTA\Durty Cloth Tool\clothproject_mpfemale**
Output path: **D:\Users\Owen\Desktop\GTA\Durty Cloth Tool**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **True**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **5**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`


This is the second time since the updates its happened, just by trying to load a project that has never had this issue before

**Comment by DurtyFree** [comment]
Should be fixed in latest release v3.2 and later, please test it if possible and let me know when its not fixed :D

Get the latest version here: https://github.com/DurtyFree/durty-cloth-tool/releases
