### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

### ISSUE THREAD

**Issue by FatCatTuxedo** [DurtyFree/durty-cloth-tool#376]
I have the following error:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at jSy7jThygkKhyjws6tW.xOjcaGhVTqMQZWxcKBQ.N2Yh6lHaT3(Int64  , List`1  , List`1  , Int64  )
   at DurtyClothTool.App.ViewModels.Commands.AppearanceItem.Clothes.OptimizeClothItemCommand.Execute(Object  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

App Version: **3.1.0.3**
Project targets: **AltV**
DLC name: **gtauniverse**
Collection name: ** // **
Project path: **D:\dev\DurtyClothTool.App\gtau\clothproject_gtauniverse**
Output path: **D:\dev\DurtyClothTool.App\gtau**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here + describe reproduction steps]`

**Comment by FatCatTuxedo** [comment]
This was due to a dogshit mod, ignore
