### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by AOG-Baited** [DurtyFree/durty-cloth-tool#69]
I have the following error:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\mpatu\OneDrive\Desktop\EUP Storage\Blaze Modifications - SSPD EUP Package\stream\Male\task_001_u.ydd'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at altClothTool.App.Builders.FivemResourceBuilder.CopyClothModelToResource(ClothData clothData, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String yddPostfix) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\FivemResourceBuilder.cs:line 67
   at altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:line 51
   at altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:line 28

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Please use latest version from GitHub releases.
