### ISSUE TITLE
New leaning to code.

### ISSUE THREAD

**Issue by NolaRed85** [DurtyFree/durty-cloth-tool#75]
Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at GTAUtil.Program.GenPedDefs_CreateComponentFiles_FiveM(GenPedDefsOptions opts, String targetFileName, KeyValuePair`2 entry, Int32 textureCount)
   at GTAUtil.Program.<>c__DisplayClass27_0.<HandleGenPedDefsOptions>b__0(GenPedDefsOptions opts, GenericOptions gOpts)
   at GTAUtil.CommandLine.Parse[T](String[] args, Action`2 callback)
   at GTAUtil.Program.Main(String[] args)

**Comment by DurtyFree** [comment]
Please download latest version from GitHub releases.

**Comment by sahyatt** [comment]
Is the latest version 2.2.7?

**Comment by DurtyFree** [comment]
> Is the latest version 2.2.7?

https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.3.1
