### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by LIBROSKI** [DurtyFree/durty-cloth-tool#81]
I have the following error:
System.DivideByZeroException: Attempted to divide by zero.
   at System.Decimal.DecCalc.VarDecDiv(DecCalc& d1, DecCalc& d2)
   at System.Decimal.op_Division(Decimal d1, Decimal d2)
   at QZa9av04MApjdbRRQ5R.yZGaX6QZbs(Decimal , Decimal , QZa9av04MApjdbRRQ5R )
   at PuyWUnO19025gUTeNHd.SbPMr8OqDNRUYFS1jxd.FR6ONVv8wM()
   at PuyWUnO19025gUTeNHd.SbPMr8OqDNRUYFS1jxd.VCDOoWObUs(String  , String  )
   at PuyWUnO19025gUTeNHd.SbPMr8OqDNRUYFS1jxd.kaQDAMjdTf(String  , String  )
   at CQC9bpOE0RVDHRudJiV.yfbLvkOntA8EeyUilnd.I9EOuT1hUQ(qwL8qvnnMfAm2inOFJP  , String  , String  , ProgressDialog  )

App Version: **2.3**
Items: **0 project items (0C / 0D)**
Project targets: **2**
Collection name: **pdeup**
Output path: **F:\DEV\City4AS\pd_eup**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**

Cloth files:
[Please provide cloth files (ydd, ytd), cloth project and any other related files here]

**Comment by DurtyFree** [comment]
Please make sure to add clothes to your project before building.

This will be prevented next update.
