### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by skittle03** [DurtyFree/durty-cloth-tool#87]
I have the following error:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Downloads\MODS BAJU\Alexander-McQueen-By-Nevek\Alexander McQueen By Nevek\Male\feet_002_u.ydd'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at altClothTool.App.Builders.AltvResourceBuilder.CopyClothModelToResource(ClothData clothData, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String yddPostfix) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\AltvResourceBuilder.cs:line 70
   at altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:line 51
   at altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:line 18

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
It failed to find a cloth with this path: E:\Downloads\MODS BAJU\Alexander-McQueen-By-Nevek\Alexander McQueen By Nevek\Male\feet_002_u.ydd

Please use latest version of the tool
